const test=require('node:test'),assert=require('node:assert/strict'),A=require('../app/agenda-proposals.js');
const state={notes:[{id:'n',content:'下周二十点开会，提前十五分钟提醒。',updatedAt:12}]},run={id:'r',userMessageId:'m',captureNoteIds:['n']},value={title:'讨论',sourceNoteId:'n',quote:'下周二十点开会',start:'2026-09-22T10:00:00+08:00',end:'2026-09-22T11:00:00+08:00',timeZone:'Asia/Shanghai',frequency:'weekly',weekdays:[3],count:4,reminderMinutes:15};
test('agenda proposals are immutable reviewed snapshots with stable retry identity',()=>{const out=A.validate([value],state,run);assert.equal(out[0].status,'pending');assert.equal(out[0].sourceVersion,12);assert.equal(out[0].id,A.validate([value],state,{...run,id:'retry'})[0].id);assert.equal(out[0].documentID,'n');assert.equal(out[0].start,Date.parse(value.start));assert.equal(state.notes[0].updatedAt,12);});
test('agenda proposal scope, evidence, dates and recurrence are validated before persistence',()=>{for(const changed of [{quote:'并未出现的原话'},{sourceNoteId:'other'},{start:'2026-09-22 10:00'},{end:value.start},{timeZone:'invented'},{timeZone:'America/New_York'},{start:'2026-02-30T10:00:00+08:00'},{weekdays:[9]},{interval:0},{count:0},{reminderMinutes:-1},{until:'2020-01-01T00:00Z'}])assert.throws(()=>A.validate([{...value,...changed}],state,run));assert.throws(()=>A.validate([value],state,{...run,captureNoteIds:[]}));assert.throws(()=>A.validate([value],{notes:[{...state.notes[0],deletedAt:1}]},run));assert.throws(()=>A.validate(Array(13).fill(value),state,run));assert.deepEqual(A.validate(undefined,state,run),[]);});
test('direct chat can propose weekly events with reviewed default duration and stable identity',()=>{
 const quote='每周四下午两点半参加组会',message={id:'user',role:'user',text:quote},s={notes:[],conversations:[{id:'c',messages:[message]}]},r={userMessageId:'user',conversationId:'c'};
 const v={title:'组会',sourceMessageId:'user',quote,start:'2026-09-17T14:30:00+08:00',end:null,timeZone:'Asia/Shanghai',frequency:'weekly',weekdays:[5],location:'腾讯会议：123-4567-8901'};
 const p=A.validate([v],s,r)[0];assert.equal(p.frequency,'weekly');assert.deepEqual(p.weekdays,[5]);assert.equal(p.end-p.start,3600000);assert.equal(p.endEstimated,true);assert.equal(p.documentID,'');assert.equal(p.sourceMessageId,'user');assert.equal(p.reminderMinutes,null);assert.equal(v.end,null);
 for(const changed of [{sourceMessageId:'other'},{quote:'未提供的证据'},{start:'2026-09-17T14:30:00Z'}])assert.throws(()=>A.validate([{...v,...changed}],s,r));
 assert.throws(()=>A.validate([v],s,{...r,conversationId:'other'}));message.deletedAt=1;assert.throws(()=>A.validate([v],s,r));
});
