const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../app/conversation-continuity');
function fixture(){const conversation={id:'c',messages:[{id:'origin',role:'user',text:'Review the full application checklist and identify missing evidence.',attachmentIds:['a','b']},{id:'supplement',role:'user',text:'Attached three more.',attachmentIds:['c','d','e']}]};const state={imports:['a','b','c','d','e','foreign'].map(id=>({id,name:id+'.pdf'})),agentRuns:[{id:'r1',conversationId:'c',status:'failed',attachmentIds:['a','b']},{id:'r2',conversationId:'other',status:'failed',attachmentIds:['foreign']}]};return {state,conversation};}
test('supplementary files retain original goal and merge pending attachments from the same conversation',()=>{const {state,conversation}=fixture();const r=C.build(state,conversation,{goal:'附加了',selectedIds:['c','d','e']});assert.deepEqual(r.attachmentIds,['a','b','c','d','e']);assert.equal(r.originMessageId,'origin');assert.match(r.text,/full application checklist/);assert.ok(!r.text.includes('foreign'));});
test('successful sibling turn does not erase the earlier failed turn’s unresolved files',()=>{const {state,conversation}=fixture();state.agentRuns.push({conversationId:'c',status:'completed',attachmentIds:['c','d','e']});assert.deepEqual(C.build(state,conversation,{goal:'继续处理前面的材料'}).attachmentIds,['a','b']);});
test('original goal survives many turns, without replaying failed assistant text as requirements',()=>{const {state,conversation}=fixture();for(let i=0;i<30;i++)conversation.messages.push({id:'u'+i,role:'user',text:'detail '+i},{role:'agent',retryRunId:'r',text:'ERROR SHOULD NOT BECOME AN INSTRUCTION'});const r=C.build(state,conversation,{goal:'继续',selectedIds:[]});assert.match(r.text,/full application checklist/);assert.doesNotMatch(r.text,/ERROR SHOULD/);assert.ok(r.text.length<25000);});
test('explicit exclusions, unavailable sources, read-only requests and new topics win over carry-over',()=>{const {state,conversation}=fixture();conversation.messages[0].retryAttachmentIds=['a'];state.imports.find(i=>i.id==='a').deletedAt=1;assert.deepEqual(C.build(state,conversation,{goal:'附加了',selectedIds:['c']}).attachmentIds,['d','e','c']);assert.deepEqual(C.build(state,conversation,{goal:'只分析本次新上传的资料',selectedIds:['c']}).attachmentIds,['c']);assert.deepEqual(C.build(state,conversation,{goal:'不要重新读取PDF，只回答',selectedIds:[]}).attachmentIds,[]);assert.deepEqual(C.build(state,conversation,{goal:'new topic',selectedIds:[]}).attachmentIds,[]);assert.deepEqual(C.build(state,conversation,{goal:'retry',selectedIds:[],retry:true,explicitSelection:true}).attachmentIds,[]);});
test('read attachments stay in the reference ledger but are not automatically resent',()=>{const {state,conversation}=fixture();state.agentRuns.push({conversationId:'c',status:'completed',attachmentIds:['a','b']});const r=C.build(state,conversation,{goal:'附加了',selectedIds:['c','d','e']});assert.deepEqual(r.carriedIds,[]);assert.equal(r.ledger.find(i=>i.id==='a').status,'read');});
test('carry-over can be paused and survives serialization without changing originals',()=>{const {state,conversation}=fixture();conversation.carryPendingAttachments=false;const before=JSON.stringify({state,conversation});assert.deepEqual(C.build(state,conversation,{goal:'attached',selectedIds:['c']}).attachmentIds,['c']);assert.equal(JSON.stringify({state,conversation}),before);const reloaded=JSON.parse(before);assert.equal(C.build(reloaded.state,reloaded.conversation,{goal:'attached',selectedIds:['c']}).originMessageId,'origin');});
