const {test}=require('node:test');const assert=require('node:assert/strict');const F=require('../app/file-context');const K=require('../app/knowledge-access');const C=require('../app/conversation-continuity');
function fixture(){return {projects:[{id:'p',workspace:'课程'},{id:'q',workspace:'科研',localFolder:{id:'local-q'}}],notes:[{id:'n',title:'章节 notes',content:'before\n'+('证据\n'.repeat(6000)),projectId:'p',workspace:'课程'}],imports:[{id:'a',name:'课程.pdf',size:12,createdAt:1,projectId:'p',workspace:'课程'}],agentRuns:[]};}
test('search is case insensitive, searches paths, excludes archived projects, does not duplicate identities',()=>{const s=fixture();assert.equal(F.search(s,'NOTES')[0].id,'n');s.projects[0].archived=true;assert.deepEqual(F.search(s,''),[]);});
test('references persist across reload and follow-up, not other conversations; remove/re-add and retry are independent',async()=>{const s=fixture(),c={messages:[]};const r=await F.libraryRef(s,'note','n');F.stage(c,r);F.stage(c,r);assert.equal(F.references(c).length,1);const m={role:'user',fileReferences:F.references(c)};c.messages.push(m);F.consume(c,m.fileReferences);const restored=JSON.parse(JSON.stringify(c));assert.equal(F.references(restored).length,1);assert.equal(F.references({messages:[]}).length,0);F.remove(restored,r);assert.equal(F.references(restored).length,0);assert.equal(F.references(restored,{retry:true,message:m}).length,1);F.stage(restored,r);assert.equal(F.references(restored).length,1);});
test('note reads are frozen and paginated, later edits are not silently treated as original version',async()=>{const s=fixture(),r=await F.libraryRef(s,'note','n');const ctx=await F.prepare(s,[r]);assert.equal(ctx.initial[0].nextOffset,12000);const old=s.notes[0].content;s.notes[0].content='changed';const rest=await ctx.read({refKey:F.key(r),offset:12000});assert.equal(ctx.initial[0].text+rest.text,old);await assert.rejects(F.prepare(s,[r]),/已修改/);await assert.rejects(ctx.read({refKey:'unknown'}),/明确引用/);await assert.rejects(ctx.read({refKey:F.key(r),offset:-1}),/读取位置/);});
test('local reads bind connected project, file version and scope across paged requests',async()=>{const s=fixture(),r={type:'local',candidateId:'local-q',projectId:'q',path:'src/main.swift',title:'main.swift',version:'version-one'};const calls=[];const readLocal=async(path,payload)=>{calls.push(payload);assert.equal(payload.version,'version-one');return {version:'version-one',text:'sample',offset:payload.offset,totalChars:20000,nextOffset:12000};};const ctx=await F.prepare(s,[r],{readLocal});await ctx.read({refKey:F.key(r),offset:12000});assert.equal(calls[1].offset,12000);s.projects[1].localFolder.id='different';await assert.rejects(F.prepare(s,[r],{readLocal}),/断开/);});
test('explicit cross-project read does not broaden search or allow unselected sources',async()=>{const s=fixture();const scope={projectId:'q',workspace:'科研',explicitReferences:[{type:'note',id:'n'}]};assert.equal((await K.execute(s,scope,{type:'read',recordType:'note',id:'n'})).id,'n');await assert.rejects(K.execute(s,scope,{type:'read',recordType:'import',id:'a'}),/范围/);assert.equal(K.records(s,scope).length,0);s.notes[0].archived=true;await assert.rejects(K.execute(s,scope,{type:'read',id:'n'}),/范围/);});
test('removed import references cannot return as automatically carried failed attachments',async()=>{const s=fixture(),r=await F.libraryRef(s,'import','a');const c={messages:[{role:'user',text:'分析课程资料',attachmentIds:['a'],fileReferences:[r]}]};F.remove(c,r);assert.equal(C.build(s,c,{goal:'继续'}).attachmentIds.length,0);});
test('mention query respects caret and does not mistake email addresses for references',()=>{assert.equal(F.mention('me@example.com',14),null);assert.deepEqual(F.mention('分析 @章节 之后',6),{start:3,end:6,query:'章节'});assert.deepEqual(F.mention('@',1),{start:0,end:1,query:''});});

test('explicit refresh lets a failed turn retry the updated version while original history remains immutable',async()=>{const s=fixture(),first=await F.libraryRef(s,'note','n'),m={role:'user',fileReferences:[first]},c={messages:[m]};s.notes[0].content='corrected';const next=await F.libraryRef(s,'note','n');F.refresh(c,next);assert.equal(m.fileReferences[0].version,first.version);assert.equal(F.references(c,{retry:true,message:m})[0].version,next.version);const prepared=await F.prepare(s,F.references(c,{retry:true,message:m}));assert.equal(prepared.initial[0].text,'corrected');});
