const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { spawnSync } = require('node:child_process');
const root = path.resolve(__dirname, '..');

test('native clipboard opt-in, privacy, transactional storage and image lifecycle use injected pasteboard only', { skip: process.platform !== 'darwin', timeout: 100000 }, () => {
  const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'aibro-clipboard-test-'));
  try {
    const source = path.join(temp, 'ClipboardTests.swift'), binary = path.join(temp, 'clipboard-tests');
    fs.writeFileSync(source, String.raw`
import AppKit
import Foundation
import ImageIO
import UniformTypeIdentifiers
func nativeUI(_ zh: String, _ en: String) -> String { en }
@MainActor final class FakeBoard: NativeQuickClipboardPasteboard {
    var changeCount = 1
    var types: [String] = [NativeQuickClipboardPolicy.textType]
    var bytes = Data("pre-existing synthetic clipboard".utf8)
    var reads = 0, writes = 0
    var failWrite = false, changeWhileReading = false
    func data(forType type: String) -> Data? { reads += 1; if changeWhileReading { changeCount += 1 }; return bytes }
    func write(_ payload: NativeQuickClipboardPayload) -> Bool {
        guard !failWrite else { return false }
        writes += 1; bytes = payload.data; types = [payload.kind == .text ? NativeQuickClipboardPolicy.textType : "public.png", NativeQuickClipboardPolicy.ownMarker]; changeCount += 1
        return true
    }
    func text(_ value: String, markers: [String] = []) { bytes = Data(value.utf8); types = [NativeQuickClipboardPolicy.textType] + markers; changeCount += 1 }
    func image(_ value: Data) { bytes = value; types = ["public.png"]; changeCount += 1 }
}
@main struct ClipboardTests {
    @MainActor static func main() async throws {
        let base = URL(fileURLWithPath: CommandLine.arguments[1]).appendingPathComponent("fixtures")
        try FileManager.default.createDirectory(at: base, withIntermediateDirectories: true)
        var checks = 0
        func check(_ value: Bool, _ message: String) { checks += 1; precondition(value, message) }
        func waitUntil(_ condition: () -> Bool) async {
            for _ in 0..<2000 { if condition() { return }; try? await Task.sleep(nanoseconds: 1_000_000) }
            precondition(condition(), "Timed out")
        }
        func image(_ seed: Int) throws -> Data {
            let width = 20, height = 12
            let pixels = (0..<(width * height * 4)).map { UInt8(($0 * 17 + seed * 41) % 255) }
            let provider = CGDataProvider(data: Data(pixels) as CFData)!
            let bitmap = CGImage(width: width, height: height, bitsPerComponent: 8, bitsPerPixel: 32, bytesPerRow: width * 4,
                space: CGColorSpaceCreateDeviceRGB(), bitmapInfo: CGBitmapInfo(rawValue: CGImageAlphaInfo.premultipliedLast.rawValue), provider: provider,
                decode: nil, shouldInterpolate: false, intent: .defaultIntent)!
            let data = NSMutableData(), target = CGImageDestinationCreateWithData(data, UTType.png.identifier as CFString, 1, nil)!
            CGImageDestinationAddImage(target, bitmap, nil); precondition(CGImageDestinationFinalize(target)); return data as Data
        }
        let board = FakeBoard(), directory = base.appendingPathComponent("store")
        let store = NativeQuickClipboardStore(directory: directory, pasteboard: board, schedulesPolling: false)
        store.setAvailable(true); store.setVisible(true); await waitUntil { store.loaded }
        store.pollOnce()
        check(store.mode == .off && board.reads == 0 && store.items.isEmpty, "Construction/off state never reads pre-existing clipboard")
        await store.setMode(.recording); store.pollOnce()
        check(board.reads == 0 && store.items.isEmpty, "Explicit enable only establishes a changeCount baseline")
        board.text("Synthetic lecture reminder"); store.pollOnce(); await waitUntil { store.items.count == 1 }
        check(store.items.first?.text == "Synthetic lecture reminder", "A subsequent copy persists exact UTF-8 text")
        let first = store.items[0], reads = board.reads
        store.pollOnce(); check(board.reads == reads, "Unchanged changeCount performs no payload read")
        for marker in ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "PasswordPboardType", "app.vendor.sensitive"] {
            board.text("synthetic marked secret", markers: [marker]); store.pollOnce()
        }
        check(board.reads == reads && store.items.count == 1, "Password/sensitive markers are rejected before any payload read")
        board.text("-----BEGIN PRIVATE KEY-----\nsynthetic\n-----END PRIVATE KEY-----"); store.pollOnce()
        check(store.items.count == 1, "Unmarked PEM private keys are excluded")
        board.text("Synthetic lecture reminder"); store.pollOnce()
        await waitUntil { store.items[0].createdAt > first.createdAt }
        check(store.items.count == 1 && store.items[0].id == first.id, "Equal content moves the existing stable item instead of duplicating it")
        store.query = "LECTURE"; check(store.filteredItems.count == 1, "Text search is case-insensitive")
        store.query = "unmatched"; check(store.filteredItems.isEmpty, "Search filters without changing persistence"); store.query = ""
        await store.copy(first); let copyReads = board.reads; store.pollOnce()
        check(board.writes == 1 && board.reads == copyReads && store.notice?.contains("Copied") == true, "Successful re-copy confirms and does not re-ingest own write")
        board.failWrite = true; await store.copy(first)
        check(store.error?.contains("Copy failed") == true && store.items.count == 1, "Failed write does not claim success or remove history"); board.failWrite = false
        await store.setMode(.paused); board.text("Copied while paused"); let pausedReads = board.reads; store.pollOnce()
        await store.setMode(.recording); store.pollOnce()
        check(board.reads == pausedReads && store.items.count == 1, "Paused copies are skipped and resume takes a fresh count-only baseline")
        board.changeWhileReading = true; board.text("unstable promised content"); store.pollOnce(); board.changeWhileReading = false
        check(store.items.count == 1, "Ownership change during promised payload read is rejected")
        board.text(String(repeating: "a", count: NativeQuickClipboardPolicy.maxTextBytes + 1)); store.pollOnce()
        check(store.items.count == 1 && store.notice?.contains("too large") == true, "Oversize text is rejected rather than silently truncated")
        let png = try image(1); board.image(png); store.pollOnce(); await waitUntil { store.items.count == 2 }
        let picture = store.items.first(where: { $0.kind == .image })!
        await store.loadThumbnail(picture)
        check(picture.width == 20 && picture.height == 12 && store.thumbnails[picture.id] != nil, "ImageIO normalization and asynchronous thumbnail loading use the captured image")
        await store.copy(picture); let afterImageCopy = board.reads; store.pollOnce()
        check(board.writes == 2 && board.reads == afterImageCopy, "Image re-copy uses PNG without self-ingestion")
        await store.remove([picture.id]); check(store.items.first(where: { $0.id == picture.id })?.deletedAt != nil, "Delete is recoverable")
        store.showingTrash = true; check(store.filteredItems.count == 1, "Recently Deleted is a separate view of the same bounded store")
        await store.restore([picture.id]); store.showingTrash = false
        check(store.filteredItems.count == 2, "Restoring an image keeps its original payload and identity")
        await store.remove(Set(store.items.map(\.id))); store.showingTrash = true
        check(store.filteredItems.count == 2, "Clear moves both kinds to recoverable trash without touching system clipboard")
        await store.restore(Set(store.items.map(\.id))); store.showingTrash = false
        store.setAvailable(false); let protectedReads = board.reads, protectedWrites = board.writes
        board.text("Synthetic private workspace copy"); store.pollOnce(); await store.copy(first)
        check(store.items.isEmpty && store.thumbnails.isEmpty && board.reads == protectedReads && board.writes == protectedWrites, "Private/unavailable state removes visible history and disables read/copy")
        store.setAvailable(true); await waitUntil { store.items.count == 2 }; store.pollOnce()
        check(board.reads == protectedReads, "Unlock restores authorized history but never ingests copies made while private")
        let reopened = NativeQuickClipboardStore(directory: directory, pasteboard: board, schedulesPolling: false)
        reopened.setAvailable(true); await waitUntil { reopened.loaded }; reopened.pollOnce()
        check(reopened.items.count == 2 && board.reads == protectedReads, "App restart restores local history and establishes a fresh baseline")
        let permissions = try FileManager.default.attributesOfItem(atPath: directory.appendingPathComponent("history.json").path)[.posixPermissions] as! NSNumber
        check(permissions.intValue == 0o600, "Persisted history is owner-only")
        let rootPermissions = try FileManager.default.attributesOfItem(atPath: directory.path)[.posixPermissions] as! NSNumber
        check(rootPermissions.intValue == 0o700, "Archive directory is owner-only")
        store.shutdown(); reopened.shutdown()
        let pausedBoard = FakeBoard(), pausedFolder = base.appendingPathComponent("inflight-pause")
        let pendingStore = NativeQuickClipboardStore(directory: pausedFolder, pasteboard: pausedBoard, schedulesPolling: false)
        pendingStore.setAvailable(true); await waitUntil { pendingStore.loaded }; await pendingStore.setMode(.recording)
        pausedBoard.image(png); pendingStore.pollOnce(); await pendingStore.setMode(.paused)
        try await Task.sleep(nanoseconds: 20_000_000)
        let pausedSaved = try await NativeQuickClipboardArchive(directory: pausedFolder).load()
        check(pausedSaved.items.isEmpty && pendingStore.items.isEmpty, "Pause revokes a queued image capture before disk commit")
        await pendingStore.setMode(.recording); pausedBoard.image(png); pendingStore.pollOnce(); pendingStore.setAvailable(false)
        try await Task.sleep(nanoseconds: 20_000_000)
        let privateSaved = try await NativeQuickClipboardArchive(directory: pausedFolder).load()
        check(privateSaved.items.isEmpty && pendingStore.items.isEmpty, "Private transition revokes a queued image capture on disk, not merely in the view")
        pendingStore.shutdown()

        let archive = NativeQuickClipboardArchive(directory: base.appendingPathComponent("bounded"))
        _ = try await archive.setMode(.recording)
        for index in 0..<105 { _ = try await archive.capture(.init(kind: .text, data: Data("synthetic entry \(index)".utf8)), gate: .init()) }
        let bounded = try await archive.load()
        check(bounded.items.count == 100 && bounded.items.last?.text == "synthetic entry 5", "History keeps the latest 100 entries across all content")
        let revoked = NativeQuickClipboardCaptureGate(); revoked.revoke()
        do { _ = try await archive.capture(.init(kind: .image, data: png), gate: revoked); fatalError("Revoked capture committed") } catch is CancellationError { check(true, "Revoked capture fails at disk commit, not only the UI callback") }
        let afterRevoked = try await archive.load()
        check(afterRevoked.items == bounded.items, "A revoked image capture cannot alter persisted history")
        let boundedFiles = try FileManager.default.contentsOfDirectory(atPath: base.appendingPathComponent("bounded").path)
        check(boundedFiles == ["history.json"], "Revoked capture leaves no image or thumbnail payload on disk")
        let quotaFolder = base.appendingPathComponent("quota"), quota = NativeQuickClipboardArchive(directory: quotaFolder, diskLimit: 160000)
        _ = try await quota.setMode(.recording)
        for index in 0..<4 { _ = try await quota.capture(.init(kind: .image, data: try image(index)), gate: .init()) }
        let limited = try await quota.load(), quotaFiles = try FileManager.default.contentsOfDirectory(atPath: quotaFolder.path)
        check(limited.items.count == 2 && quotaFiles.count == 5, "Disk quota evicts old image entries and removes both original and thumbnail files")
        _ = try await quota.remove(ids: [limited.items[0].id], permanently: false)
        _ = try await quota.remove(ids: [limited.items[0].id], permanently: true)
        let afterPermanent = try await quota.load(), filesAfterPermanent = try FileManager.default.contentsOfDirectory(atPath: quotaFolder.path)
        check(afterPermanent.items.count == 1 && filesAfterPermanent.count == 3, "Permanent deletion removes image and thumbnail only after manifest commit")
        let orphan = quotaFolder.appendingPathComponent(String(repeating: "f", count: 64) + ".png")
        try Data("synthetic orphan".utf8).write(to: orphan)
        _ = try await NativeQuickClipboardArchive(directory: quotaFolder, diskLimit: 160000).load()
        check(!FileManager.default.fileExists(atPath: orphan.path), "Restart cleans uncommitted owned image orphans without touching unrelated files")

        let corruptFolder = base.appendingPathComponent("corrupt")
        try FileManager.default.createDirectory(at: corruptFolder, withIntermediateDirectories: true)
        let corruptFile = corruptFolder.appendingPathComponent("history.json"), malformed = Data("not json".utf8)
        try malformed.write(to: corruptFile)
        do { _ = try await NativeQuickClipboardArchive(directory: corruptFolder).load(); fatalError("Corrupt file loaded") } catch { check(true, "Corrupt manifests fail closed") }
        check(try Data(contentsOf: corruptFile) == malformed, "Corrupt data is not silently replaced")
        let outside = base.appendingPathComponent("outside.txt"); try Data("synthetic external file".utf8).write(to: outside)
        let linkedFolder = base.appendingPathComponent("linked")
        try FileManager.default.createSymbolicLink(at: linkedFolder, withDestinationURL: quotaFolder)
        do { _ = try await NativeQuickClipboardArchive(directory: linkedFolder).load(); fatalError("Followed folder symlink") } catch { check(true, "Symlink archive directories are refused") }
        let remaining = afterPermanent.items[0], imageFile = quotaFolder.appendingPathComponent(remaining.id + ".png")
        try FileManager.default.removeItem(at: imageFile); try FileManager.default.createSymbolicLink(at: imageFile, withDestinationURL: outside)
        do { _ = try await quota.payload(id: remaining.id); fatalError("Followed payload symlink") } catch { check(true, "Re-copy refuses a tampered image symlink") }
        check(try String(contentsOf: outside) == "synthetic external file", "External files remain unchanged")
        let failFolder = base.appendingPathComponent("write-failure"), failing = NativeQuickClipboardArchive(directory: failFolder)
        _ = try await failing.setMode(.recording)
        let manifest = failFolder.appendingPathComponent("history.json")
        try FileManager.default.removeItem(at: manifest); try FileManager.default.createDirectory(at: manifest, withIntermediateDirectories: false)
        do { _ = try await failing.capture(.init(kind: .image, data: png), gate: .init()); fatalError("Failed commit accepted") } catch { check(true, "A failed manifest commit is reported") }
        let failureState = try await failing.load(), failureFiles = try FileManager.default.contentsOfDirectory(atPath: failFolder.path)
        check(failureState.items.isEmpty && failureFiles == ["history.json"], "Uncommitted image files are removed and in-memory history is retained")
        check(NSApp == nil, "Tests neither launch an app nor read the real NSPasteboard.general")
        print("PASS: \(checks) injected clipboard privacy, persistence and image assertions")
    }
}
`);
    const names = ['NativeQuickClipboard.swift', 'NativeQuickClipboardArchive.swift', 'NativeQuickClipboardView.swift', 'NativeQuickClipboardPasteBack.swift'];
    const built = spawnSync('xcrun', ['swiftc', '-swift-version', '5', '-target', 'arm64-apple-macosx14.0', '-parse-as-library', ...names.map(name => path.join(root, 'native/Sources/AIBro', name)), source, '-o', binary], { encoding: 'utf8', timeout: 75000 });
    assert.equal(built.status, 0, built.stdout + built.stderr + (built.error?.message || ''));
    const run = spawnSync(binary, [temp], { encoding: 'utf8', timeout: 20000 });
    assert.equal(run.status, 0, run.stdout + run.stderr + (run.error?.message || ''));
    assert.match(run.stdout, /PASS: \d+ injected clipboard/); console.log(run.stdout.trim());
  } finally { fs.rmSync(temp, { recursive: true, force: true }); }
});
