const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const {webcrypto,randomUUID}=require('node:crypto');
const Core=require('../app/workstation-core.js'),CitationEvidence=require('../app/citation-evidence.js'),ContentLifecycle=require('../app/content-lifecycle.js');
const source=fs.readFileSync(require.resolve('../native/Resources/quick-links.js'),'utf8'),clone=v=>JSON.parse(JSON.stringify(v)),rid=()=>'quick_link_'+randomUUID();
const PNG='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLttAAAAABJRU5ErkJggg==';
function fixture(options={}){
 const calls={save:0,network:0},context={state:options.state||{imports:[],notes:[],tasks:[],papers:[],links:[],trash:[],attachments:[],agentRuns:[],conversations:[],projects:[{id:'p',name:'Research',workspace:'科研'}],ui:{}},storageHydrated:true,serverConflict:false,purgeTrash:{},URL,TextEncoder,CustomEvent:class{},document:{dispatchEvent(){}},saveDocumentDurably:async()=>{calls.save++;return options.save?options.save(context,calls):true;},fetch:async(path,input)=>{calls.network++;assert.equal(path,'/__bookmark-metadata');const p=JSON.parse(input.body);if(options.fetch)return options.fetch(p,context,calls);return {ok:true,json:async()=>result(p)};}};
 context.window={crypto:webcrypto,WorkstationCore:Core,CitationEvidence,ContentLifecycle,PrivateMode:{isOn:()=>!!context.privateMode}};vm.runInNewContext(source,context);return {context,calls,get state(){return context.state;},request:p=>context.window.NativeQuickLinks.request(p)};
}
function result(p,patch={}){return {id:p.bookmark.id,bookmarkRequestId:p.bookmark.requestId,title:'Website research',description:'A website description',finalUrl:'https://example.org/actual',iconDataUrl:PNG,iconStatus:'ready',...patch};}
async function add(f,patch={}){await f.request({action:'add',requestId:rid(),url:'https://example.org/reading',title:'My title',folder:'Reading',workspace:'科研',projectId:'p',...patch});return f.state.imports.at(-1);}
async function command(f,id){const row=(await f.request({action:'list'})).rows.find(r=>r.id===id);return {action:'metadata',requestId:rid(),items:[{id,expectedVersion:row.version}]};}
async function row(f,id){return (await f.request({action:'list'})).rows.find(r=>r.id===id);}
test('explicit metadata works for saved originals and preserves human title, content, scope and original-file fields',async()=>{const f=fixture(),r=await add(f);Object.assign(r,{content:'Saved text',pages:[{page:1,text:'Saved text'}],fileStored:true,parser:'web',originalName:'Original.html',tags:['human']});const before=clone(r);assert.equal(f.calls.network,0);const response=await f.request(await command(f,r.id));assert.equal(response.metadataStatus,'ready');assert.deepEqual(clone(r),before);assert.equal((await row(f,r.id)).iconDataUrl,PNG);assert.equal((await row(f,r.id)).siteDescription,'A website description');assert.equal(f.calls.network,1);assert.equal(f.calls.save,3);});
test('untitled quick bookmark receives the real website title, without changing grouping or original name',async()=>{const f=fixture(),r=await add(f,{title:''}),original=r.originalName;await f.request(await command(f,r.id));assert.equal(r.name,'Website research');assert.equal(r.originalName,original);assert.equal(r.folderPath,'Reading');assert.equal(r.content,'');});
test('icon failure still saves page metadata and retains an older matching icon',async()=>{let broken=false;const f=fixture({fetch:async p=>({ok:true,json:async()=>result(p,broken?{iconDataUrl:'',iconStatus:'unavailable',description:'New description'}:{})})}),r=await add(f);await f.request(await command(f,r.id));broken=true;const response=await f.request(await command(f,r.id));assert.equal(response.metadataStatus,'ready');assert.equal(response.iconStatus,'unavailable');assert.equal((await row(f,r.id)).iconDataUrl,PNG);assert.equal((await row(f,r.id)).siteDescription,'New description');});
test('offline retry keeps body and cached icon; saved failure is replayed without another network request',async()=>{let offline=false;const f=fixture({fetch:async p=>{if(offline)throw Error('offline');return {ok:true,json:async()=>result(p)};}}),r=await add(f);r.content='Existing';await f.request(await command(f,r.id));offline=true;const p=await command(f,r.id);assert.equal((await f.request(p)).metadataStatus,'failed');await f.request(p);assert.equal(f.calls.network,2);assert.equal(r.content,'Existing');assert.equal((await row(f,r.id)).iconDataUrl,PNG);});
test('durable bookmark save is required before network',async()=>{let okay=true;const f=fixture({save:()=>okay}),r=await add(f);okay=false;assert.equal((await f.request(await command(f,r.id))).reason,'storage_failed');assert.equal(f.calls.network,0);});
test('privacy, scope, body change or entire workspace replacement discards late metadata',async()=>{for(const mutate of [ctx=>ctx.privateMode=true,ctx=>ctx.state.projects[0].private=true,ctx=>ctx.state.imports[0].projectId=null,ctx=>ctx.state.imports[0].content='Later user edit',ctx=>ctx.state=clone(ctx.state)]){const f=fixture({fetch:async(p,ctx)=>{mutate(ctx);return {ok:true,json:async()=>result(p)};}}),r=await add(f);const response=await f.request(await command(f,r.id));assert.notEqual(response.status,'saved');assert.equal(f.state.ui.nativeQuickLinkMetadata,undefined);}});
test('malformed or mismatched image receipt is rejected, never passed as a remote image',async()=>{for(const patch of [{id:'wrong'},{iconDataUrl:'https://tracker.invalid/x',iconStatus:'ready'},{iconDataUrl:'data:image/svg+xml;base64,PHN2Zz4=',iconStatus:'ready'},{description:'x'.repeat(501)}]){const f=fixture({fetch:async p=>({ok:true,json:async()=>result(p,patch)})}),r=await add(f);assert.equal((await f.request(await command(f,r.id))).metadataStatus,'failed');assert.equal((await row(f,r.id)).iconDataUrl,'');}});
test('lost final save ACK persists the exact result and does not fetch or overwrite later edits on replay',async()=>{let durable;const f=fixture({save:(ctx,calls)=>{durable=clone(ctx.state);return calls.save!==3;}}),r=await add(f),p=await command(f,r.id);assert.equal((await f.request(p)).reason,'storage_failed');const next=fixture({state:durable});next.state.imports[0].name='Later manual';assert.equal((await next.request(p)).metadataStatus,'ready');assert.equal(next.calls.network,0);assert.equal(next.state.imports[0].name,'Later manual');assert.equal((await row(next,r.id)).iconDataUrl,PNG);});
test('cached metadata stays bound to exact URL and original identity; private rows do not expose it',async()=>{const f=fixture(),r=await add(f);await f.request(await command(f,r.id));const identity=r.quickLinkIdentity;r.quickLinkIdentity='replacement';assert.equal((await row(f,r.id)).iconDataUrl,'');r.quickLinkIdentity=identity;r.url='https://example.org/different';assert.equal((await row(f,r.id)).iconDataUrl,'');r.private=true;assert.equal((await f.request({action:'list'})).rows.length,0);});
test('metadata for ordinary imported web sources is bound to the stable identity assigned by the durable mutation',async()=>{const f=fixture();f.state.imports.push({id:'normal-web-import',name:'Human import',url:'https://example.org/paper',content:'Keep',fileStored:true,updatedAt:1,workspace:'科研',projectId:'p'});await f.request(await command(f,'normal-web-import'));assert.equal((await row(f,'normal-web-import')).iconDataUrl,PNG);assert.equal(f.state.imports[0].name,'Human import');});
test('local metadata cache is bounded and evicts only cache, never original records',async()=>{const f=fixture();for(let i=0;i<130;i++){const r=await add(f,{url:'https://example.org/'+i});await f.request(await command(f,r.id));}assert.equal(Object.keys(f.state.ui.nativeQuickLinkMetadata).length,128);assert.equal(f.state.imports.length,130);assert.ok(JSON.stringify(f.state.ui.nativeQuickLinkMetadata).length<4*1024*1024);});
test('main-library manual rename without the island flag is never overwritten',async()=>{const f=fixture(),r=await add(f,{title:''});r.name='Edited in the main library';assert.equal(r.quickLinkTitleEdited,false);await f.request(await command(f,r.id));assert.equal(r.name,'Edited in the main library');});
test('empty website metadata reports no usable fields instead of a fake result',async()=>{const f=fixture({fetch:async p=>({ok:true,json:async()=>result(p,{title:'',description:'',iconDataUrl:'',iconStatus:'unavailable'})})}),r=await add(f);const before=clone(r),response=await f.request(await command(f,r.id));assert.equal(response.hasMetadata,false);assert.deepEqual(clone(r),before);});
