const test=require('node:test'),assert=require('node:assert/strict'),M=require('../app/project-memory');
const state=()=>({projects:[{id:'p',name:'Synthetic research',workspace:'科研',description:'Compare sampling methods'},{id:'q',name:'Other',workspace:'科研'}],notes:[],tasks:[{id:'t',projectId:'p',title:'Compare',status:'todo'}],conversations:[{id:'c',projectId:'p',messages:[{id:'m',role:'user',text:'先跑基线，再比较新方法。'}]}],trash:[]});
const run=()=>({id:'r',projectId:'p',conversationId:'c',userMessageId:'m',goal:'Compare sampling',status:'completed',startedAt:Date.now(),results:[{type:'task',id:'t',text:'Created comparison'}]});
test('daily log and plan survive a new context and are idempotent without chat history',()=>{const s=state(),r=run();M.settle(s,r);const before=JSON.stringify(s);M.settle(s,r);assert.equal(JSON.stringify(s),before);s.conversations=[];const ctx=M.context(s,'p');assert.match(ctx.text,/Compare sampling/);assert.match(ctx.text,/Created comparison/);assert.equal(ctx.entries.length,3);assert.equal(M.context(s,'q').entries.length,0);assert.equal(M.context(s,'missing').entries.length,0);});
test('only exact user quotes in the current project can become proposed memory',()=>{const s=state(),r=run();const update={type:'decision',text:'先基线后新方法',messageId:'m',quote:'先跑基线，再比较新方法。'};r.memoryUpdates=M.validateUpdates(s,r,[update]);M.settle(s,r);const note=M.find(s,'p','long');assert.ok(note.aiDraft);assert.doesNotMatch(note.content,/先基线/);assert.match(note.aiDraft.content,/先跑基线/);assert.doesNotMatch(M.context(s,'p').text,/先基线/);assert.throws(()=>M.validateUpdates(s,r,[{...update,quote:'编造的原话'}]),/准确/);s.conversations[0].projectId='q';assert.throws(()=>M.validateUpdates(s,r,[update]),/准确/);});
test('manual plan sections are preserved and edited generated index becomes a draft',()=>{const s=state();const n=M.refreshPlan(s,'p');n.content+='\n## 人工说明\nPreserve me';s.tasks.push({id:'t2',title:'Next',projectId:'p'});M.refreshPlan(s,'p');assert.match(n.content,/Preserve me/);assert.match(n.content,/Next/);n.content=n.content.replace('Compare','My manual version');s.tasks[1].title='Latest';M.refreshPlan(s,'p');assert.match(n.content,/My manual version/);assert.ok(n.aiDraft);assert.match(n.aiDraft.content,/Latest/);});
test('deleted memory is not resurrected, unavailable Markdown is excluded, failed run records facts only',()=>{const s=state(),r=run();M.settle(s,r);const long=M.find(s,'p','long');s.notes=s.notes.filter(n=>n!==long);s.trash.push({data:{notes:[long]}});r.id='r2';r.status='failed';r.error='Transport stopped';r.results=[];M.settle(s,r);assert.equal(s.notes.some(n=>n.id===long.id),false);assert.match(M.context(s,'p').text,/Transport stopped/);s.notes.forEach(n=>n.wikiFileError='missing');assert.equal(M.context(s,'p').entries.length,0);});
test('memory pagination covers all content without treating the first page as full coverage',()=>{const s=state(),n=M.ensure(s,s.projects[0],'long');n.content='x'.repeat(33000)+'ENDING';let text='',offset=0;do{const p=M.context(s,'p',{offset});text+=p.text;offset=p.nextOffset;}while(offset!==null);assert.match(text,/ENDING$/);assert.ok(text.length>33000);});
test('a routed result cannot transfer the original project memory or another project output',()=>{const s=state(),r=run();r.memoryProjectId='p';r.projectId='q';s.tasks.push({id:'foreign',projectId:'q',title:'Private other'});r.results.push({type:'task',id:'foreign',text:'Private other'});M.settle(s,r);assert.equal(M.context(s,'q').entries.length,0);assert.doesNotMatch(M.context(s,'p').text,/Private other/);});
test('extending proposed memory preserves the prior draft',()=>{const s=state(),r=run();r.memoryUpdates=M.validateUpdates(s,r,[{type:'decision',text:'Baseline first',messageId:'m',quote:'先跑基线'}]);M.settle(s,r);const n=M.find(s,'p','long'),previous=n.aiDraft.content;r.id='r2';M.settle(s,r);assert.equal(n.aiDraftHistory.at(-1).content,previous);assert.doesNotMatch(n.content,/Baseline first/);});
test('refreshing a project with a pending draft preserves proposed prose and approved content',()=>{
 const s=state(),n=M.refreshPlan(s,'p'),approved=n.content;
 n.aiDraft={title:n.title,content:approved+'\n## Pending experiment\nKeep the preregistered hypothesis.',sourceNoteIds:['source'],createdAt:10};
 s.tasks.push({id:'next',projectId:'p',title:'Run second experiment',status:'todo'});
 const draftBefore=structuredClone(n.aiDraft);M.refreshPlan(s,'p');
 assert.equal(n.content,approved);assert.match(n.aiDraft.content,/Run second experiment/);assert.match(n.aiDraft.content,/Keep the preregistered hypothesis/);
 assert.deepEqual(n.aiDraftHistory.at(-1).content,draftBefore.content);assert.deepEqual(n.aiDraft.sourceNoteIds,['source']);
 const after=JSON.stringify(n);M.refreshPlan(s,'p');assert.equal(JSON.stringify(n),after);
});
test('manual removal of the draft index is respected on later automatic updates',()=>{
 const s=state(),n=M.refreshPlan(s,'p');n.aiDraft={content:'# Curated plan\nAn intentional hand-written plan.'};
 const before=JSON.stringify(n);s.tasks.push({id:'next',projectId:'p',title:'Next'});M.refreshPlan(s,'p');assert.equal(JSON.stringify(n),before);
});
test('literal replacement metacharacters in task titles cannot corrupt plan or pending draft',()=>{
 const s=state(),n=M.refreshPlan(s,'p');n.aiDraft={content:n.content+'\n## Preserve\nDraft'};s.tasks[0].title='Match $& then $` and $\'';
 M.refreshPlan(s,'p');assert.ok(n.aiDraft.content.includes(s.tasks[0].title));assert.equal(n.aiDraft.content.split('<!-- aibro:project-index -->').length,2);
});
