const test=require('node:test'),assert=require('node:assert/strict'),W=require('../app/research-wiki.js'),M=require('../app/wiki-maintenance.js');
test('stable targets survive moved source and destination; repairs exclude code and existing drafts',()=>{
 const body='[B](b.md#result)\n`[B](b.md)`\n~~~md\n[B](b.md)\n~~~\n';
 const s={notes:[{id:'a',content:body,title:'A'},{id:'b',content:'B',title:'B'}],_wikiFiles:{a:{path:'methods/new/a.md',links:{'b.md#result':'b'}},b:{path:'concepts/b.md'}}};
 assert.equal(W.resolveLink(s,'a','b.md#result'),'b');const rows=M.proposals(s);assert.equal(rows.length,1);assert.equal(rows[0].count,1);assert.equal(rows[0].after,body.replace('[B](b.md#result)','[B](../../concepts/b.md#result)'));assert.equal(s.notes[0].content,body);
 s.notes[0].aiDraft={content:'pending'};assert.equal(M.proposals(s).length,0);delete s.notes[0].aiDraft;s.notes[1].archived=true;assert.equal(M.proposals(s).length,0);assert.equal(W.resolveLink(s,'a','b.md#result'),null);
});
test('purged targets never resolve to a different note reusing their old path',()=>{const s={notes:[{id:'a',content:'[B](b.md)',title:'A'},{id:'new',title:'replacement'}],_wikiFiles:{a:{path:'a.md',links:{'b.md':'old'}},new:{path:'b.md'}}};assert.equal(W.resolveLink(s,'a','b.md'),null);assert.equal(M.proposals(s).length,0);});
test('directory originals remain source references and disappear after archival or provenance removal',()=>{const s={projects:[{id:'p'}],notes:[{id:'n',projectId:'p',wikiSourceLinks:{'figure.png':'img'},sourceAttachmentIds:['img']}],imports:[{id:'img',projectId:'p',mimeType:'image/png'}]};assert.equal(W.resolveSource(s,'n','figure.png').id,'img');s.imports[0].archived=true;assert.equal(W.resolveSource(s,'n','figure.png'),null);delete s.imports[0].archived;s.notes[0].sourceAttachmentIds=[];assert.equal(W.resolveSource(s,'n','figure.png'),null);s.notes[0].sourceAttachmentIds=['img'];s.projects[0].archived=true;assert.equal(W.resolveSource(s,'n','figure.png'),null);});
