/* Capture first; AI transformations always preserve the original note. */
(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.CaptureNotes=api;})(globalThis,root=>{
 'use strict';const F=root.FileContext||(typeof require==='function'?require('./file-context.js'):null);
 const t=(zh,en)=>root.WorkstationI18n?.getLanguage?.()==='en'?en:zh;
 const items=state=>(state.notes||[]).filter(n=>n.kind==='随记'&&F.active(n));
 function projectIds(state,note){const activeProjects=new Set((state.projects||[]).filter(F.active).map(p=>p.id));return [...new Set([note.projectId,...[...(state.notes||[]),...(state.tasks||[])].filter(n=>F.active(n)&&(n.sourceNoteIds||[]).includes(note.id)).map(n=>n.projectId),...(state.imports||[]).filter(n=>F.active(n)&&(note.sourceAttachmentIds||[]).includes(n.id)).map(n=>n.projectId)])].filter(id=>activeProjects.has(id));}
 function day(value){const d=new Date(value);return Number.isNaN(d.valueOf())?'':d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
 function search(state,query='',filters={}){const terms=query.toLowerCase().trim().split(/\s+/).filter(Boolean);return items(state).filter(n=>{const date=day(n.createdAt);return terms.every(x=>(n.title+' '+n.content+' '+(n.tags||[]).join(' ')).toLowerCase().includes(x))&&(!filters.from||date>=filters.from)&&(!filters.to||date<=filters.to)&&(!filters.tag||(n.tags||[]).includes(filters.tag))&&(!filters.project||projectIds(state,n).includes(filters.project));}).sort((a,b)=>b.createdAt-a.createdAt);}
 function write(state,{id,version,text,tags=[],hasFiles=false,removeAttachmentIds=[]},{uid,now=Date.now()}={}){
  if(typeof text!=='string'||text.length>200000)throw Error('随记正文最多 200,000 个字符。');if(!text.trim()&&!hasFiles)throw Error('先写一点内容，或添加附件。');
  let note=id?items(state).find(n=>n.id===id):null;if(id&&(!note||note.updatedAt!==version))throw Error('这条随记已有变化或已删除，请重新打开，当前输入仍保留。');
  if(!note){note={id:uid('note'),kind:'随记',workspace:'日常',projectId:null,createdAt:now,sourceAttachmentIds:[],content:''};state.notes.push(note);}
  if(note.content!==text&&note.content)note.revisionHistory=[...(note.revisionHistory||[]),{content:note.content,title:note.title,at:now,reason:'随记手动编辑'}];
  note.sourceAttachmentIds=(note.sourceAttachmentIds||[]).filter(id=>!removeAttachmentIds.includes(id));
  Object.assign(note,{title:text.trim().split('\n')[0].slice(0,70)||t('附件随记','Attached capture'),content:text,tags:[...new Set(tags.map(x=>String(x).trim()).filter(Boolean))],updatedAt:Math.max(now,(note.updatedAt||0)+1),userEdited:true,userEditedAt:now});return note;
 }
 function selection(state,ids){const notes=ids.map(id=>items(state).find(n=>n.id===id));if(!notes.length||notes.some(n=>!n))throw Error('所选随记已变化，请重新选择。');const attachments=[...new Set(notes.flatMap(n=>n.sourceAttachmentIds||[]))];if(attachments.some(id=>!F.available(state,'import',id)))throw Error('随记附件已删除或归档，请先恢复附件或移除对应引用。');return {notes:structuredClone(notes),attachments,key:JSON.stringify(notes.map(n=>[n.id,n.updatedAt]).sort((a,b)=>a[0].localeCompare(b[0])))};}
 function linkResults(state,run,results){const sources=(run.captureNoteIds||[]).filter(id=>items(state).some(n=>n.id===id));if(!sources.length)return;for(const r of results||[]){if(!['note','task'].includes(r.type)||sources.includes(r.id)||r.operation==='deleted')continue;const entry=state[r.type==='note'?'notes':'tasks'].find(n=>n.id===r.id);if(!entry||!F.active(entry))continue;const target=r.operation==='drafted'&&entry.aiDraft?entry.aiDraft:entry;target.sourceNoteIds=[...new Set([...(target.sourceNoteIds||[]),...sources])];if(target!==entry)continue;for(const id of sources)if(!state.links.some(l=>l.sourceId===id&&l.targetId===entry.id&&l.relation==='derived-from-capture'))state.links.push({id:'capture_'+id+'_'+entry.id,sourceId:id,sourceType:'note',targetId:entry.id,targetType:r.type,relation:'derived-from-capture',createdAt:Date.now()});}}
 let hooks,host,composer,list,searchBox,input,tagInput,status,saveButton,filesBox,fromInput,toInput,tagFilter,projectFilter,selectVisible,clearSelection;let removed=[],chosen=new Set(),files=[],editing=null,version=null,busy=false,analyzing=false,hydrated=false;
 const el=(tag,cls,text)=>{const n=root.document.createElement(tag);n.className=cls||'';if(text!==undefined)n.textContent=text;return n;};
 const btn=(label,fn,cls='secondary')=>{const b=el('button',cls,label);b.type='button';b.onclick=fn;return b;};
 function stash(){if(!hooks)return;hooks.getState().ui.captureDraft={text:input.value,tags:tagInput.value,id:editing,version,pendingFiles:files.length,removeAttachmentIds:removed};hooks.save();}
 function clear(){editing=null;version=null;input.value='';tagInput.value='';files=[];removed=[];stash();renderFiles();}
 function edit(note){if(busy)return;if(input.value.trim()||files.length){hooks.toast(t('先保存当前输入，再打开另一条随记。','Save the current draft before editing another capture.'));return;}removed=[];editing=note.id;version=note.updatedAt;input.value=note.content;tagInput.value=(note.tags||[]).join(', ');stash();renderFiles();input.focus();}
 function renderFiles(){filesBox.replaceChildren();for(const file of files){const chip=el('span','capture-file');chip.append(el('span','',file.name),btn('×',()=>{files=files.filter(f=>f!==file);stash();renderFiles();},'capture-remove'));filesBox.append(chip);}if(editing){const note=items(hooks.getState()).find(n=>n.id===editing);for(const id of note?.sourceAttachmentIds||[]){const file=hooks.getState().imports.find(f=>f.id===id);if(removed.includes(id))continue;const chip=el('span','capture-file');chip.append(btn(file?.name||t('附件不可用','Unavailable attachment'),()=>hooks.open('import',id),'capture-remove'),btn('×',()=>{removed.push(id);stash();renderFiles();},'capture-remove'));filesBox.append(chip);}}}
 function attach(incoming){if(busy||!hydrated)return;files.push(...Array.from(incoming||[]));stash();renderFiles();status.textContent=t('附件尚未保存，请点击保存随记。','Attachments are not saved yet. Choose Save capture.');}
 async function commit(){if(busy||!hydrated)return;if(hooks.importBusy()){hooks.toast(t('请等附件导入完成后再保存。','Wait for the current upload to finish.'));return;}busy=true;saveButton.disabled=true;input.disabled=true;tagInput.disabled=true;
  try{const note=write(hooks.getState(),{id:editing,version,text:input.value,removeAttachmentIds:removed,tags:tagInput.value.split(/[,，]/),hasFiles:!!files.length||!!items(hooks.getState()).find(n=>n.id===editing)?.sourceAttachmentIds?.filter(id=>!removed.includes(id)).length},{uid:hooks.uid});editing=note.id;version=note.updatedAt;stash();await hooks.persist();
   if(files.length){const result=await hooks.importFiles(files,note.id);if(!result)throw Error('附件导入未开始，请重试。');files=result.failedFiles||[];version=items(hooks.getState()).find(n=>n.id===editing)?.updatedAt;await hooks.persist();}
   if(files.length){stash();renderFiles();status.textContent=t('原文与成功附件已保存；请重试剩余附件。','Text and successful uploads are saved. Retry the remaining files.');}else{clear();status.textContent=t('已保存到随记。','Saved to captures.');}render();
  }catch(error){status.textContent=error.message;stash();renderFiles();}finally{busy=false;saveButton.disabled=false;input.disabled=false;tagInput.disabled=false;}
 }
 async function analyze(mode){if(busy||analyzing||hooks.aiBusy())return;analyzing=true;render();try{const picked=selection(hooks.getState(),[...chosen]);await hooks.analyze(picked,mode);}catch(e){hooks.toast(e.message);}finally{analyzing=false;render();}}
 function hydrate(){if(hydrated||!hooks?.ready())return;const draft=hooks.getState().ui.captureDraft||{};input.value=draft.text||'';tagInput.value=draft.tags||'';editing=draft.id||null;version=draft.version??null;removed=draft.removeAttachmentIds||[];hydrated=true;if(draft.pendingFiles)status.textContent=t('上次有尚未保存的附件，请重新选择；文字草稿已恢复。','Please reselect attachments that were not saved. Your text draft was restored.');renderFiles();}
 function render(){if(!hooks||!host)return;hydrate();
  host.querySelector('.page-heading>div').textContent=t('随记 · 让零散的想法，慢慢长成线索。','Captures · Give small thoughts room to grow.');
  input.placeholder=t('此刻想到什么？文字、链接，或者拖入图片与文件…','What’s on your mind? Add text, links, images or files…');tagInput.placeholder=t('标签，用逗号分隔（可选）','Tags, comma separated (optional)');
  saveButton.textContent=t('保存随记','Save capture');host.querySelector('.capture-actions button').textContent=t('添加图片 / 文件','Add images / files');
  searchBox.placeholder=t('搜索随记与标签…','Search captures and tags…');
  input.setAttribute('aria-label',t('随记内容','Capture text'));tagInput.setAttribute('aria-label',t('随记标签','Capture tags'));searchBox.setAttribute('aria-label',searchBox.placeholder);
  for(const [node,zh,en] of [[fromInput,'开始日期','From'],[toInput,'结束日期','Through'],[tagFilter,'标签','Tag'],[projectFilter,'关联项目','Linked project']])node.parentElement.querySelector('span').textContent=t(zh,en);
  for(const [mode,zh,en]of[['organize','AI 整理','Organize'],['ideas','发现关联与 Idea','Explore ideas'],['actions','提炼任务与日程','Plan next steps'],['wiki','沉淀为科研 Wiki','Save to research Wiki'],['experiment','设计实验','Design experiment']])host.querySelector('[data-capture-ai='+mode+']').textContent=t(zh,en);
  input.disabled=tagInput.disabled=saveButton.disabled=busy||!hydrated;list.replaceChildren();const state=hooks.getState();chosen=new Set([...chosen].filter(id=>items(state).some(n=>n.id===id)));const updateOptions=(select,options,label)=>{const value=select.value;const signature=JSON.stringify(options)+label;if(select.dataset.options!==signature){select.replaceChildren(new Option(label,''),...options.map(([id,title])=>new Option(title,id)));select.dataset.options=signature;select.value=value;}};updateOptions(tagFilter,[...new Set(items(state).flatMap(n=>n.tags||[]))].sort().map(x=>[x,x]),t('全部标签','All tags'));updateOptions(projectFilter,(state.projects||[]).filter(F.active).map(p=>[p.id,p.name||p.title]),t('全部关联项目','All linked projects'));
  const records=search(state,searchBox.value,{from:fromInput.value,to:toInput.value,tag:tagFilter.value,project:projectFilter.value});const visibleSelected=records.filter(n=>chosen.has(n.id)).length;selectVisible.textContent=t('选择筛选结果','Select results')+' · '+records.length;selectVisible.disabled=!records.length;clearSelection.textContent=t('清空选择','Clear selection');clearSelection.disabled=!chosen.size;host.querySelector('.capture-count').textContent=items(state).length+' '+t('条随记','captures');host.querySelector('.capture-selection').textContent=chosen.size?t('已选 ','Selected ')+chosen.size+(chosen.size>visibleSelected?t('（其中隐藏 ',' (hidden ')+(chosen.size-visibleSelected)+')':''):t('选择随记，让想法产生关联。','Select captures to explore their connections.');host.querySelectorAll('[data-capture-ai]').forEach(b=>b.disabled=!chosen.size||analyzing||hooks.aiBusy());

  if(!records.length)list.append(el('p','capture-empty',t('记下一个念头、贴上一个链接，或者拖入一份资料。','Save a thought, paste a link, or drop a file.')));
  for(const note of records){const card=el('article','capture-card');card.dataset.captureId=note.id;const head=el('header'),check=el('input');check.type='checkbox';check.checked=chosen.has(note.id);check.setAttribute('aria-label',t('选择随记：','Select capture: ')+note.title);check.onchange=()=>{check.checked?chosen.add(note.id):chosen.delete(note.id);render();};head.append(check,el('time','',new Date(note.createdAt).toLocaleString(root.WorkstationI18n?.getLanguage?.()==='en'?'en':'zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})));const title=el('h2','',note.title);title.dataset.userContent='';card.append(head,title);const lines=note.content.trim().split('\n');const remainder=lines[0]===note.title?lines.slice(1).join('\n').trim():note.content;if(remainder){const body=el('p','capture-text',remainder);body.dataset.userContent='';card.append(body);}
   const urls=[...new Set(note.content.match(/https?:\/\/[^\s<>"']+/g)||[])];for(const url of urls){try{const u=new URL(url);const a=el('a','capture-url',u.hostname);a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';card.append(a);}catch{}}
   const attachments=el('div','capture-attachments');for(const id of note.sourceAttachmentIds||[]){const file=F.available(state,'import',id);const b=btn(file?.name||t('附件不可用','Unavailable attachment'),()=>hooks.open('import',id),'capture-file');b.dataset.userContent='';b.disabled=!file;b.dataset.openImport=id;attachments.append(b);}card.append(attachments);
   const outputs=[...(state.notes||[]).map(n=>({...n,type:'note'})),...(state.tasks||[]).map(n=>({...n,type:'task'}))].filter(n=>F.active(n)&&(n.sourceNoteIds||[]).includes(note.id));if(outputs.length){const links=el('div','capture-derived');links.append(el('small','',t('由此产生','Derived from this capture')));for(const result of outputs)links.append(btn(result.title,()=>hooks.open(result.type,result.id),'capture-file'));card.append(links);}
   if(note.tags?.length){const tags=el('p','capture-tags',note.tags.map(x=>'#'+x).join('  '));tags.dataset.userContent='';card.append(tags);}const foot=el('footer');foot.append(btn(t('查看','Open'),()=>hooks.open('note',note.id)),btn(t('编辑','Edit'),()=>edit(note)),btn(t('移入回收站','Move to trash'),()=>hooks.remove(note.id)));root.CaptureAgenda?.append(foot,note);card.append(foot);list.append(card);
  }
 }
 function init(value){hooks=value;host=root.document.getElementById('captures');const heading=el('div','page-heading');heading.append(el('div','',t('随记 · 让零散的想法，慢慢长成线索。','Captures · Give small thoughts room to grow.')),el('span','capture-count'));host.append(heading);
  composer=el('section','capture-composer');input=el('textarea');input.placeholder=t('此刻想到什么？文字、链接，或者拖入图片与文件…','What’s on your mind? Add text, links, images or files…');input.setAttribute('aria-label',t('随记内容','Capture text'));tagInput=el('input');tagInput.placeholder=t('标签，用逗号分隔（可选）','Tags, comma separated (optional)');tagInput.setAttribute('aria-label',t('随记标签','Capture tags'));filesBox=el('div','capture-attachments');const picker=el('input');picker.type='file';picker.multiple=true;picker.hidden=true;picker.onchange=()=>{attach(picker.files);picker.value='';};const actions=el('div','capture-actions');saveButton=btn(t('保存随记','Save capture'),commit,'primary');saveButton.dataset.captureSave='true';actions.append(btn(t('添加图片 / 文件','Add images / files'),()=>picker.click()),saveButton);status=el('p','capture-status');status.setAttribute('role','status');composer.append(input,tagInput,filesBox,picker,actions,status);host.append(composer);
  input.oninput=tagInput.oninput=stash;input.onkeydown=e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();void commit();}};
  composer.ondragover=e=>{e.preventDefault();e.stopPropagation();};composer.ondrop=e=>{e.preventDefault();e.stopPropagation();attach(e.dataTransfer.files);};composer.onpaste=e=>{if(e.clipboardData?.files.length){e.preventDefault();e.stopPropagation();attach(e.clipboardData.files);}};
  const toolbar=el('div','capture-toolbar');searchBox=el('input');searchBox.type='search';searchBox.placeholder=t('搜索随记与标签…','Search captures and tags…');searchBox.setAttribute('aria-label',searchBox.placeholder);searchBox.oninput=render;toolbar.append(searchBox,el('span','capture-selection'));for(const [mode,zh,en]of[['organize','AI 整理','Organize'],['ideas','发现关联与 Idea','Explore ideas'],['actions','提炼任务与日程','Plan next steps'],['wiki','沉淀为科研 Wiki','Save to research Wiki'],['experiment','设计实验','Design experiment']]){const b=btn(t(zh,en),()=>analyze(mode));b.dataset.captureAi=mode;toolbar.append(b);}host.append(toolbar);const filters=el('div','capture-filters');const field=(label,node)=>{const wrap=el('label');wrap.append(el('span','',label),node);filters.append(wrap);};fromInput=el('input');toInput=el('input');for(const date of [fromInput,toInput]){date.type='date';date.onchange=render;}field(t('开始日期','From'),fromInput);field(t('结束日期','Through'),toInput);tagFilter=el('select');projectFilter=el('select');for(const select of [tagFilter,projectFilter])select.onchange=render;field(t('标签','Tag'),tagFilter);field(t('关联项目','Linked project'),projectFilter);selectVisible=btn('',()=>{for(const n of search(hooks.getState(),searchBox.value,{from:fromInput.value,to:toInput.value,tag:tagFilter.value,project:projectFilter.value}))chosen.add(n.id);render();});clearSelection=btn('',()=>{chosen.clear();render();});selectVisible.dataset.captureSelectVisible='';clearSelection.dataset.captureClearSelection='';filters.append(selectVisible,clearSelection);host.append(filters);list=el('div','capture-grid');host.append(list);root.document.addEventListener('workstation-language-change',render);renderFiles();render();
 }
 return {items,search,projectIds,write,selection,linkResults,init,render,attach,hydrate};
});
