(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.ProjectBoard=api;})(globalThis,root=>{
'use strict';const statuses=['todo','in_progress','blocked','done'],labels={todo:['待开始','To do'],in_progress:['进行中','In progress'],blocked:['受阻','Blocked'],done:['已完成','Done']},active=n=>n&&!n.archived&&!n.deletedAt;
function move(state,id,projectId,status,version,now=Date.now()){
 const task=state.tasks.find(t=>t.id===id&&active(t));if(!task||task.projectId!==projectId||!state.projects.some(p=>p.id===projectId&&active(p)))throw Error('任务或所属项目已变化，请刷新。');if(JSON.stringify(task)!==version)throw Error('任务已更新，请按最新状态重试。');if(!statuses.includes(status))throw Error('无效任务状态。');const before={...task};task.status=status;task.completedAt=status==='done'?(task.completedAt||now):null;task.updatedAt=now;return {task,before};
}
let hooks,pending=false,drag=null;
const t=(zh,en)=>root.WorkstationI18n?.getLanguage?.()==='en'?en:zh;
function render(projectId){const list=document.getElementById('projectTasks');if(!list)return;let toolbar=document.getElementById('projectBoardToolbar'),board=document.getElementById('projectTaskBoard');if(!toolbar){toolbar=document.createElement('div');toolbar.id='projectBoardToolbar';toolbar.className='project-board-toolbar';board=document.createElement('div');board.id='projectTaskBoard';board.className='project-task-board';list.before(toolbar,board);}
 const state=hooks.getState(),mode=state.ui.projectTaskView||'list',el=(tag,text,cls)=>{const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;},button=(text,fn)=>{const b=el('button',text,'secondary');b.type='button';b.onclick=fn;return b;};
 toolbar.replaceChildren();for(const [value,label]of [['list',t('列表','List')],['board',t('看板','Board')]]){const b=button(label,()=>{state.ui.projectTaskView=value;hooks.save();render(projectId);});b.setAttribute('aria-pressed',String(mode===value));toolbar.append(b);}toolbar.append(el('span',t('拖动卡片切换状态；也可使用卡片下方的移动按钮。','Drag cards between columns, or use their move buttons.')));
 list.hidden=mode==='board';board.hidden=mode!=='board';board.replaceChildren();if(mode!=='board')return;
 const change=async(id,status,version)=>{if(pending)return;pending=true;let result;try{result=move(hooks.getState(),id,projectId,status,version);await hooks.persist();hooks.renderAll();hooks.toast(t('任务状态已保存','Task status saved'));}catch(e){if(result&&hooks.getState().tasks.find(n=>n.id===result.task.id)===result.task)Object.assign(result.task,result.before);hooks.toast(e.message);render(projectId);}finally{pending=false;}};
 const tasks=state.tasks.filter(n=>active(n)&&n.projectId===projectId);
 for(const status of statuses){const column=el('section','','project-board-column');column.dataset.boardStatus=status;const rows=tasks.filter(n=>(statuses.includes(n.status)?n.status:'todo')===status);column.append(el('h3',t(...labels[status])+' · '+rows.length));column.ondragover=e=>{if(drag?.projectId===projectId){e.preventDefault();e.dataTransfer.dropEffect='move';column.classList.add('is-over');}};column.ondragleave=e=>{if(!column.contains(e.relatedTarget))column.classList.remove('is-over');};column.ondrop=e=>{e.preventDefault();column.classList.remove('is-over');if(drag?.projectId===projectId)void change(drag.id,status,drag.version);drag=null;};
 for(const task of rows){const card=el('article','','project-board-card');card.draggable=true;card.dataset.boardTask=task.id;const version=JSON.stringify(task);card.ondragstart=e=>{drag={id:task.id,projectId,version};e.dataTransfer.setData('text/plain',task.id);e.dataTransfer.effectAllowed='move';card.classList.add('is-dragging');};card.ondragend=()=>{drag=null;card.classList.remove('is-dragging');board.querySelectorAll('.is-over').forEach(n=>n.classList.remove('is-over'));};
 const title=button(task.title,()=>hooks.open(task.id));title.className='project-board-title';card.append(title);if(task.dueAt)card.append(el('time',new Date(task.dueAt).toLocaleString()));const readiness=root.TaskDependencies?.readiness(state,task);if(readiness&&!readiness.ready)card.append(el('p',t(`${readiness.blockedBy.length} 项前置任务未完成`,`${readiness.blockedBy.length} prerequisites incomplete`),'project-board-dependency'));
 const controls=el('div','','project-board-moves');for(const destination of statuses.filter(s=>s!==status)){const b=button(t('移至 ','Move to ')+t(...labels[destination]),()=>change(task.id,destination,version));b.disabled=pending;controls.append(b);}card.append(controls);column.append(card);}
 if(!rows.length)column.append(el('p',t('暂无任务','No tasks'),'muted'));board.append(column);}
}
return {move,render,init:h=>{hooks=h;}};
});
