(function(root){'use strict';const W=root.ResearchWiki,t=(zh,en)=>root.WorkstationI18n?.getLanguage?.()==='en'?en:zh;
const FIELD_LABELS={definition:'Definition and scope',distinctions:'Related concepts and differences',description:'Data and tasks',task:'Evaluation task',protocol:'Protocol and metrics',purpose:'Purpose and audience',question:'Research question',method:'Method and contributions',evidence:'Evidence and source locations',limitations:'Limitations and scope',principle:'Core principle',assumptions:'Assumptions and prerequisites',procedure:'Implementation and procedure',hypothesis:'Hypothesis',setup:'Setup and controls',versions:'Code and data versions',results:'Metrics and results',interpretation:'Interpretation and limitations',symptom:'Problem and symptoms',attempts:'Attempts and outcomes',conditions:'Reproduction conditions',feedback:'Original feedback and sources',response:'Response and decisions',validation:'Validation plan and evidence',status:'Status',connections:'Connections and inspiration',observations:'Observations and evidence',inferences:'Inferences to validate',contradictions:'Conflicts and invalidated conclusions',nextSteps:'Next steps and open questions'};
let hooks,host,search,filter='',projectId,dialog,saving=false,newId=null;
const el=(tag,cls,text)=>{const n=document.createElement(tag);n.className=cls||'';if(text!==undefined)n.textContent=text;return n;};
const button=(text,fn,cls='secondary')=>{const b=el('button',cls,text);b.type='button';b.onclick=fn;return b;};
function init(h){hooks=h;host=document.getElementById('wiki');host.append(el('header','wiki-heading'),el('div','wiki-scopes'),el('div','wiki-types'));search=el('input','wiki-search');search.type='search';search.setAttribute('aria-label','Search research Wiki');search.oninput=renderCards;host.append(search);const layout=el('div','wiki-layout'),tree=el('nav','wiki-tree');tree.setAttribute('aria-label',t('科研知识目录','Research knowledge directory'));layout.append(tree,el('div','wiki-grid'));host.append(layout);document.addEventListener('workstation-language-change',render);render();}
function render(){if(!host)return;const heading=host.querySelector('header');heading.replaceChildren();const text=el('div');text.append(el('small','wiki-eyebrow','RESEARCH / WIKI'),el('h1','',t('科研 Wiki','Research Wiki')),el('p','',t('让研究有积累，让下一次从已知出发。','Build on what you know, across every conversation.')));const storage=el('div','wiki-storage');storage.append(button(hooks.getState()._wikiEnabled?t('刷新 Markdown','Refresh Markdown'):t('建立 Markdown Wiki','Create Markdown Wiki'),async()=>{try{await hooks.refresh(!hooks.getState()._wikiEnabled);render();hooks.toast(t('Wiki 已同步','Wiki synchronized'));}catch(e){hooks.toast(e.message);}}));if(root.WikiMigrationUI)storage.append(button(t('迁入已有笔记 / Markdown','Import notes / Markdown'),()=>root.WikiMigrationUI.open()));if(root.WikiMaintenance)storage.append(button(t('检查移动链接','Check moved links'),()=>root.WikiMaintenance.open()));if(root.WikiExport)storage.append(button(t("导出目录与原件","Export Wiki and sources"),()=>root.WikiExport.open(W.entries(hooks.getState(),{projectId,type:filter,query:search.value}).map(n=>n.id))));if(root.ResearchInspector)storage.append(button(t('知识检查','Knowledge checks'),()=>root.ResearchInspector.openHealth({projectId})),button(t('检索试验','Retrieval lab'),()=>root.ResearchInspector.openSearch({projectId})),button(t('资料处理','Source processing'),()=>root.ResearchInspector.openSources({projectId})));text.append(storage);if(hooks.getState()._wikiError)text.append(el('p','wiki-pending',hooks.getState()._wikiError));heading.append(text,button(t('＋ 新建条目','＋ New entry'),()=>compose(),'primary'));search.placeholder=t('搜索问题、方法、证据或失败经验…','Search questions, methods, evidence or lessons…');
 const scopes=host.querySelector('.wiki-scopes');scopes.replaceChildren();const options=[['all',t('全部科研','All research')],['',t('独立条目','Unassigned')],...(hooks.getState().projects||[]).filter(p=>W.active(p)&&p.workspace==='科研').map(p=>[p.id,p.name])];if(projectId&&!options.some(x=>x[0]===projectId))projectId=undefined;
 for(const [id,name]of options){const b=button(name,()=>{projectId=id==='all'?undefined:id||null;render();},'wiki-scope');b.setAttribute('aria-pressed',String((id==='all'&&projectId===undefined)||(id===''&&projectId===null)||id===projectId));if(id&&id!=='all')b.dataset.userContent='';scopes.append(b);}
 const kinds=host.querySelector('.wiki-types');kinds.replaceChildren();for(const [key,kind]of [['',{zh:'全部',en:'All',icon:'◌'}],...Object.entries(W.TYPES)]){const count=W.entries(hooks.getState(),{projectId,type:key}).length;const b=button(`${kind.icon}  ${t(kind.zh,kind.en)}  ${count}`,()=>{filter=key;render();},'wiki-kind');b.dataset.wikiType=key;b.setAttribute('aria-pressed',String(filter===key));kinds.append(b);}renderCards();}
function renderCards(){renderTree();const grid=host.querySelector('.wiki-grid');grid.replaceChildren();const state=hooks.getState(),notes=W.entries(state,{projectId,type:filter,query:search.value});if(!notes.length){const empty=el('div','wiki-empty');empty.append(el('h2','',t('从一个问题，一次尝试开始。','Start with a question or an experiment.')),el('p','',t('论文导读会在这里显示。你也可以记录方法、失败经验或 Review 反馈。','Paper guides appear here, alongside methods, lessons and review feedback.')));grid.append(empty);}
 for(const note of notes){const kind=W.TYPES[W.typeOf(note)],card=el('article','wiki-card');card.dataset.wikiNote=note.id;const meta=el('div','wiki-meta');meta.append(el('span','wiki-badge',`${kind.icon} ${t(kind.zh,kind.en)}`),el('time','',new Date(note.updatedAt).toLocaleDateString()));const title=el('h2','',note.title);title.dataset.userContent='';const excerpt=el('p','wiki-excerpt',String(note.content||'').split('\n').filter(x=>x.trim()&&!/^\s*[#>]/.test(x)&&x.trim()!=='未记录。').slice(0,3).join('\n'));excerpt.dataset.userContent='';card.append(meta,title,excerpt);
 const relation=W.related(state,note),owner=state.projects.find(p=>p.id===note.projectId);const label=el('p','wiki-owner',owner?.name||t('独立科研条目','Unassigned research'));label.dataset.userContent='';card.append(label);card.append(el('small','wiki-provenance',`${t('来源','Sources')} ${(note.sourceAttachmentIds||[]).length+relation.sources.length} · ${t('反向关联','Backlinks')} ${relation.backlinks.length}`));if(note.aiDraft)card.append(el('p','wiki-pending',t('有待审阅修改 · 正文保留当前版本','Changes awaiting review · current version preserved')));
 if(note.wikiFileError)card.append(el('p','wiki-pending',t('文件不可读，当前显示缓存：','File unavailable; showing cached text: ')+note.wikiFileError));const actions=el('footer');if(note.wikiFileError)actions.append(button(t('恢复已保存正文','Restore saved content'),async()=>{try{await hooks.restore(note.id);render();}catch(e){hooks.toast(e.message);}}));actions.append(button(t('阅读与编辑','Read & edit'),()=>hooks.open(note.id)),button(t('与 AI 继续研究','Continue with AI'),()=>hooks.continue(note.id).catch(e=>hooks.toast(e.message))),button(t('移入回收站','Move to trash'),()=>hooks.remove(note.id)));if(root.WikiMerge)actions.append(button(t('合并条目','Merge entries'),()=>root.WikiMerge.open(note.id)));if(root.ResearchInspector)actions.append(button(t('来源与关联','Sources and links'),()=>root.ResearchInspector.openRelations(note.id)));card.append(actions);grid.append(card);}
}
function renderTree(){
 const tree=host.querySelector('.wiki-tree'),state=hooks.getState();const expanded=new Set([...tree.querySelectorAll('details[open]')].map(d=>d.dataset.path));const known=new Set([...tree.querySelectorAll('details')].map(d=>d.dataset.path));tree.replaceChildren();const nodes=new Map();
 const folder=(path)=>{let parent=tree,key='';for(const name of path){key+='/'+name;if(!nodes.has(key)){const d=el('details');d.dataset.path=key;d.open=!known.has(key)||expanded.has(key);d.append(el('summary','',name));parent.append(d);nodes.set(key,d);}parent=nodes.get(key);}return parent;};
 const projects=new Set((state.projects||[]).filter(p=>W.active(p)&&p.workspace==='科研').map(p=>p.id));
 const scoped=n=>W.active(n)&&(!n.projectId? n.workspace==='科研':projects.has(n.projectId))&&(projectId===undefined||(n.projectId||null)===projectId);
 const q=search.value.toLocaleLowerCase().trim();
 for(const note of (state.notes||[]).filter(scoped)){
  const type=W.typeOf(note);if(filter&&type!==filter)continue;if(q&&!`${note.title} ${note.content}`.toLocaleLowerCase().includes(q))continue;
  const diskPath=state._wikiFiles?.[note.id]?.path;const path=diskPath?diskPath.split('/').slice(0,-1):type==='paper'?['sources','papers']:type?[({method:'methods',concept:'concepts',dataset:'datasets',benchmark:'benchmarks',output:'outputs',experiment:'experiments',failure:'failures',review:'reviews',idea:'questions'})[type]]:['notes'];
  const b=button(note.title,()=>hooks.open(note.id),'wiki-tree-file');b.dataset.userContent='';b.title=note.title;b.dataset.wikiTreeNote=note.id;b.dataset.openNote=note.id;folder(path).append(b);
 }
 for(const source of (state.imports||[]).filter(scoped)){
  const name=source.name||source.originalName||source.id;if(q&&!name.toLocaleLowerCase().includes(q))continue;
  const parts=String(source.folderPath||'').split('/').filter(x=>x&&x!=='.'&&x!=='..');const b=button(name,()=>hooks.openSource(source.id),'wiki-tree-file');b.dataset.userContent='';b.title=name;b.dataset.wikiTreeSource=source.id;folder(source.wikiVaultPath?source.wikiVaultPath.split('/').slice(0,-1):['sources','files',...parts]).append(b);
 }
 if(!tree.children.length)tree.append(el('p','wiki-empty',t('暂无匹配资料','No matching documents')));
}
function compose(){if(dialog?.open)return;newId=null;dialog?.remove();dialog=el('dialog','wiki-dialog');dialog.setAttribute('aria-label',t('新建科研 Wiki 条目','New research Wiki entry'));const draft=hooks.getState().ui.wikiDraft||{type:filter||'experiment',projectId:projectId||null,sections:{}};let type=W.TYPES[draft.type]?draft.type:'experiment',pid=draft.projectId||null,values={...(draft.sections||{})};const title=el('input','wiki-title');title.placeholder=t('为这个研究条目起个名字','Name this research entry');title.value=draft.title||'';title.setAttribute('aria-label',title.placeholder);const fields=el('div','wiki-fields'),types=el('div','wiki-types'),projects=el('div','wiki-scopes'),status=el('p','wiki-status');status.setAttribute('role','status');
 const stash=()=>{hooks.getState().ui.wikiDraft={type,projectId:pid,title:title.value,sections:values};hooks.save();};title.oninput=stash;
 const draw=()=>{types.replaceChildren();for(const [id,kind]of Object.entries(W.TYPES)){const b=button(t(kind.zh,kind.en),()=>{type=id;stash();draw();},'wiki-kind');b.setAttribute('aria-pressed',String(type===id));b.dataset.createWikiType=id;types.append(b);}projects.replaceChildren();for(const [id,name]of [[null,t('独立科研条目','Unassigned research')],...hooks.getState().projects.filter(p=>W.active(p)&&p.workspace==='科研').map(p=>[p.id,p.name])]){const b=button(name,()=>{pid=id;stash();draw();},'wiki-scope');b.setAttribute('aria-pressed',String(pid===id));projects.append(b);}fields.replaceChildren();for(const [key,label]of Object.entries(W.fields(type))){const row=el('label','wiki-field'),area=el('textarea');area.value=values[key]||'';area.placeholder=t('尚无依据可以留空，不必填满。','Leave blank when evidence is unavailable.');area.dataset.wikiSection=key;area.oninput=()=>{values[key]=area.value;stash();};row.append(el('span','',t(label,FIELD_LABELS[key]||label)),area);fields.append(row);}};
 const save=button(t('保存条目','Save entry'),async()=>{if(saving)return;saving=true;dialog.querySelectorAll('input,textarea,button').forEach(n=>n.disabled=true);try{const sections=Object.fromEntries(Object.keys(W.fields(type)).map(k=>[k,values[k]||'']));const note=hooks.create({wikiType:type,title:title.value,sections,projectId:pid,noteId:newId});newId=note.id;await hooks.persist();delete hooks.getState().ui.wikiDraft;hooks.save();dialog.close();render();await hooks.open(note.id);}catch(e){status.textContent=e.message;}finally{saving=false;dialog.querySelectorAll('input,textarea,button').forEach(n=>n.disabled=false);}},'primary');save.dataset.wikiSave='true';const actions=el('footer');actions.append(button(t('稍后继续','Continue later'),()=>dialog.close()),save);dialog.addEventListener('cancel',e=>{if(saving)e.preventDefault();});dialog.append(el('h2','',t('留下可复用的研究记忆','Save reusable research memory')),types,projects,title,fields,status,actions);draw();document.body.append(dialog);dialog.showModal();title.focus();}
root.ResearchWikiUI={init,render,compose};
})(globalThis);
