import React from 'react';
import { Button, Badge, Caption, Heading } from './halaska-kit.jsx';
const t = (zh, en) => /^en(?:-|$)/i.test(document.documentElement.lang || '') ? en : zh;
const labels = { todo: ['待开始','To do'], in_progress: ['进行中','In progress'], done: ['完成','Done'], blocked: ['受阻','Blocked'], low: ['低','Low'], medium: ['中','Medium'], high: ['高','High'], '日常': ['日常','Daily'], '课程': ['课程','Courses'], '科研': ['科研','Research'] };
const optionLabel = option => labels[option.label] ? t(...labels[option.label]) : option.label;
function Editor({ spec, disabled, id, onChange }) {
  const shared = { id, disabled, 'aria-label': spec.label };
  const labelFor = option => ['workflowCategory', 'patch.workflowCategory'].includes(spec.key) ? option.label : optionLabel(option);
  if (spec.type === 'textarea') return <textarea {...shared} rows={5} value={spec.value} onChange={e => onChange(e.target.value)} maxLength={200000} />;
  if (spec.type === 'tasks') return <select {...shared} multiple size={Math.min(4, Math.max(2, spec.options.length))} value={spec.value} onChange={e => onChange([...e.target.selectedOptions].map(option => option.value))}>{spec.options.map(option => <option key={option.value} value={option.value}>{labelFor(option)}</option>)}</select>;
  if (spec.options) return <select {...shared} value={spec.value} onChange={e => onChange(spec.type === 'project' && e.target.value === '__standalone' ? null : e.target.value)}>{spec.type !== 'project' && !spec.options.some(option => option.value === '') && <option value="">{t('未指定','Unspecified')}</option>}{spec.options.map(option => <option key={option.value} value={option.value}>{labelFor(option)}</option>)}</select>;
  // Preserve the original ISO precision/timezone and numeric timestamps until a
  // deliberate edit. Native datetime-local would silently strip these values.
  return <input {...shared} type="text" value={spec.value} onChange={e => onChange(spec.type === 'date' && !e.target.value ? null : e.target.value)} maxLength={4000} placeholder={spec.type === 'date' ? '2026-09-24 / 2026-09-24T14:30:00+08:00' : ''} />;
}
function reviewValue(value, field, row) {
  if (field.path === 'patch.workflowCategory') return row.fields.find(spec => spec.key === field.path)?.options?.find(option => option.value === (value ?? ''))?.label || String(value);
  if (value === undefined || value === null || value === '') return t('未设置','Not set');
  if (Array.isArray(value)) {
    if (!value.length) return t('空列表','Empty list');
    if (field.path === 'patch.checklist') return value.map(item => typeof item==='string' ? '☐ '+item : `${item?.done?'☑':'☐'} ${item?.text??JSON.stringify(item)}`).join('\n');
    const options=row.fields.find(spec=>spec.key===field.path)?.options||[];
    return value.map(item=>options.find(option=>option.value===item)?.label||String(item)).join('\n');
  }
  if (typeof value==='object') return JSON.stringify(value,null,2);
  return labels[value] ? t(...labels[value]) : String(value);
}
function FieldValue({ value, field, row }) {
  const text=reviewValue(value,field,row);
  return text.length>140 || text.split('\n').length>3 ? <details className="plan-field-long"><summary><span className="plan-field-preview">{text.slice(0,110)}{text.length>110?'…':''}</span><span className="plan-field-expand">{t('展开全文','Show full value')}</span></summary><pre>{text}</pre></details> : <span className="plan-field-value">{text}</span>;
}
function FieldReviewTable({ row, disabled, onDecideField }) {
  const fields=row.fieldReview.fields, count=fields.filter(field=>field.accepted&&!field.unchanged).length;
  return <div className="plan-field-review"><div className="plan-field-review-heading"><strong>{t('逐字段审阅','Review each field')}</strong><span>{t(`${count} 项保留 · ${fields.length} 项字段`,`${count} retained · ${fields.length} fields`)}</span></div><table><caption className="sr-only">{row.title} · {t('原值与提议','Current and proposed values')}</caption><thead><tr><th scope="col">{t('字段','Field')}</th><th scope="col">{t('执行前','Before')}</th><th scope="col">{t('提议值','Proposed')}</th><th scope="col">{t('决定','Decision')}</th></tr></thead><tbody>{fields.map(field=><tr key={field.path} data-review-field={field.path} className={(field.unchanged?'is-unchanged':field.accepted?'is-accepted':'is-rejected')+(field.edited?' is-edited':'')}><th scope="row">{field.label}{field.edited&&<span className="plan-field-edited">{t('已编辑','Edited')}</span>}</th><td className="plan-field-before" data-label={t('执行前','Before')}><FieldValue value={field.before} field={field} row={row}/></td><td className="plan-field-after" data-label={t('提议值','Proposed')}><FieldValue value={field.after} field={field} row={row}/>{field.edited&&<details className="plan-field-original"><summary>{t('审阅起始提议','Proposal when review began')}</summary><FieldValue value={field.original} field={field} row={row}/></details>}</td><td className="plan-field-decision" data-label={t('决定','Decision')}>{field.unchanged?<span className="plan-field-noop">{t('无变化','Unchanged')}</span>:<div role="group" aria-label={t(`决定是否修改${field.label}`,`Decide whether to change ${field.label}`)}><Button size="sm" variant="ghost" disabled={disabled} aria-pressed={field.accepted} aria-label={t(`采用${field.label}提议`,`Accept ${field.label} proposal`)} onClick={()=>onDecideField(row.key,field.path,true)}>{t('采用','Accept')}</Button><Button size="sm" variant="ghost" disabled={disabled} aria-pressed={!field.accepted} aria-label={t(`保留${field.label}原值`,`Keep original ${field.label}`)} onClick={()=>onDecideField(row.key,field.path,false)}>{t('保留原值','Keep original')}</Button></div>}</td></tr>)}</tbody></table><p className="plan-field-review-note">{t('保留原值会从待执行动作中移除该字段。后续步骤的“执行前”包含前面已采用的修改。','Keeping the original removes that field from the pending action. Later “Before” values include accepted changes from earlier steps.')}</p></div>;
}
export function PlanReviewSurface({ runId, draft, rows, canSessionApprove, canReview, onEdit, onDecideField, onToggle, onMove, onSave, onApprove, onSessionApprove, onReject, onReview, onRecheck, onReload, onCopy }) {
  const included = rows.filter(row => row.included && row.fieldReview?.effective!==false), blocked = draft.busy || draft.stale || draft.dirty || !draft.validation.ok;
  function escape(event) { if (event.key !== 'Escape' || event.nativeEvent.isComposing || event.isComposing || event.keyCode === 229) return; const details = event.target.closest('.plan-review-step > details'); if (details?.open) { event.preventDefault(); event.stopPropagation(); details.open = false; details.querySelector('summary')?.focus(); } }
  return <section className="plan-review" aria-label={t('执行计划与批准范围','Execution plan and approval scope')} onKeyDown={escape}>
    <header className="plan-review-heading"><div><Caption>{t('执行前核对','REVIEW BEFORE EXECUTION')}</Caption><Heading level={3}>{t('核对执行计划','Review what will change')}</Heading></div><Badge variant="warning">{draft.dirty ? t('未保存修改','Unsaved changes') : t('等待批准','Awaiting approval')}</Badge></header>
    <p className="plan-review-intro">{t('只批准保留的步骤。展开可修改字段；取消或调整顺序后会重新检查整份计划。','Approve only the retained steps. Expand a step to edit its fields. The entire plan is checked after removal or reordering.')}</p>
    <div className="plan-review-scope"><strong>{t(`本次范围 · ${included.length} / ${rows.length} 步`,`This approval · ${included.length} / ${rows.length} steps`)}</strong><span>{[...new Set(included.map(row => row.project + ' · ' + row.workspace))].join(' / ')}</span></div>
    <ol className="plan-review-steps">{rows.map((row, index) => <li className={'plan-review-step' + (!row.included ? ' is-excluded' : '') + (row.fieldReview?.suppressed ? ' is-suppressed' : '') + (row.danger ? ' is-destructive' : '')} key={row.key} data-step-key={row.key}>
      <div className="plan-review-step-top"><label className="plan-review-include"><input type="checkbox" checked={row.included} disabled={draft.busy || draft.stale} onChange={e => onToggle(row.key, e.target.checked)} /><span className="sr-only">{t('保留步骤','Keep step')} {index + 1}: {row.title}</span></label><span className="plan-review-number" aria-hidden="true">{String(index + 1).padStart(2, '0')}</span><strong>{row.label}</strong><div className="plan-review-move"><Button size="sm" variant="ghost" disabled={draft.busy || draft.stale || index === 0} aria-label={t(`上移步骤 ${index + 1}`,`Move step ${index + 1} up`)} onClick={() => onMove(row.key, -1)}>↑</Button><Button size="sm" variant="ghost" disabled={draft.busy || draft.stale || index === rows.length - 1} aria-label={t(`下移步骤 ${index + 1}`,`Move step ${index + 1} down`)} onClick={() => onMove(row.key, 1)}>↓</Button></div></div>
      <h4 title={row.title}>{row.title}</h4><p className="plan-review-target">{row.project} <span>·</span> {row.workspace}{row.targetId && <code>{row.targetId}</code>}</p><p className="plan-review-effect">{row.consequence}</p>{row.fieldReview?.fields.length>0?<FieldReviewTable row={row} disabled={!row.included||draft.busy||draft.stale} onDecideField={onDecideField}/>:row.changes?.length > 0 && <dl className="plan-review-changes">{row.changes.map((change,i) => <div key={i}><dt>{change.label}</dt><dd>{change.before !== undefined && <><del>{labels[change.before] ? t(...labels[change.before]) : change.before}</del><span aria-label={t('修改为','changes to')}> → </span></>}{labels[change.after] ? t(...labels[change.after]) : change.after}</dd></div>)}</dl>}{row.fieldReview?.suppressed&&<p className="plan-field-suppressed" role="status">{t('没有保留实际修改，此步骤不会执行。','No actual changes remain; this step will not execute.')}</p>}{row.excerpt && <p className="plan-review-excerpt">{row.excerpt}</p>}{row.sources.length > 0 && <p className="plan-review-sources">{t('关联来源：','Linked sources: ')}{row.sources.join(' · ')}</p>}
      <details><summary>{row.fields.length ? t('查看与调整字段','Review and edit fields') : t('查看完整操作内容','View full action')}</summary><div className="plan-review-fields">{row.fields.map((spec, fi) => { const id = `plan-${runId}-${index}-${fi}`; return <label key={spec.key} htmlFor={id} className={spec.type === 'textarea' || spec.type === 'tasks' ? 'is-wide' : ''}><span>{spec.label}{spec.inherited && <small>{t('沿用原值','Current value')}</small>}</span><Editor id={id} spec={spec} disabled={!row.included || draft.busy || draft.stale} onChange={value => onEdit(row.key, spec.key, value)} />{spec.type === 'tasks' && <small>{t('按住 ⌘ / Ctrl 可多选或取消；前置步骤被移除时必须明确修改依赖。','Hold ⌘ / Ctrl to select or remove dependencies. Removing a prerequisite requires an explicit dependency change.')}</small>}</label>; })}</div><details className="plan-review-parameters"><summary>{t('完整提议参数（含未采用字段）','Full proposal parameters (including rejected fields)')}</summary><pre>{JSON.stringify(row.action, null, 2)}</pre></details></details>
    </li>)}</ol>
    {!draft.validation.ok && <div className="plan-review-error" role="alert"><strong>{t('计划尚不能执行','This plan cannot execute yet')}</strong><p>{draft.validation.error}</p><small>{t('请恢复缺失步骤、调整顺序或明确修改引用；不会自动修补依赖。','Restore a missing step, change the order, or explicitly update references. Dependencies are never repaired automatically.')}</small></div>}
    {!!draft.validation.results?.length && <details className="plan-review-results"><summary>{t('预期结果 · 执行后才会保存','Expected results · saved only after execution')}</summary><ul>{draft.validation.results.map((result, index) => <li key={index}>{result.text}</li>)}</ul></details>}
    {draft.error && <p className="plan-review-error" role="alert">{draft.error}</p>}
    {draft.stale && <div className="plan-review-recovery"><Button size="sm" variant="secondary" disabled={draft.busy} onClick={onRecheck}>{t('核对最新对象','Review latest objects')}</Button><Button size="sm" variant="ghost" disabled={draft.busy} onClick={onReload}>{t('重新载入计划','Reload plan')}</Button><Button size="sm" variant="ghost" onClick={onCopy}>{t('复制当前草稿','Copy current draft')}</Button></div>}
    {draft.previousDraft && <p className="plan-review-notice">{t('重新载入前的草稿仍在本窗口。','The draft from before reloading remains in this window.')} <Button size="sm" variant="ghost" onClick={onCopy}>{t('复制旧草稿','Copy previous draft')}</Button></p>}
    <p className="plan-review-notice" role="status" aria-live="polite">{draft.busy ? t('正在保存或批准，请稍候…','Saving or approving…') : draft.notice || (draft.dirty ? t('修改仅保留在本窗口。先保存计划，再批准。','Changes stay in this window. Save the plan before approving.') : t('批准只适用于上面这份计划及已核对的对象版本。','Approval applies only to the plan above and the reviewed object versions.'))}</p>
    <footer className="plan-review-footer"><div><Button size="sm" variant="ghost" disabled={draft.busy} onClick={onReject}>{t('拒绝执行','Reject')}</Button>{canReview && <Button size="sm" variant="secondary" disabled={blocked} onClick={onReview}>{t('请审查者核对','Ask reviewer')}</Button>}</div><div>{draft.dirty && <Button size="sm" variant="secondary" disabled={draft.busy || draft.stale || (!draft.validation.ok&&!draft.validation.canSaveEmpty)} onClick={onSave}>{t('保存计划','Save plan')}</Button>}<Button size="sm" variant="accent" disabled={blocked} onClick={onApprove}>{t(`批准 ${included.length} 步`,`Approve ${included.length} ${included.length===1?'step':'steps'}`)}</Button></div></footer>
    {canSessionApprove && <div className="plan-review-session"><Button size="sm" variant="ghost" disabled={blocked} onClick={onSessionApprove}>{t('本会话允许同类动作','Allow similar actions in this conversation')}</Button><small>{t('范围由现有权限规则决定；不可逆动作仍逐次确认。','Scope follows existing permission rules. Irreversible actions still require individual approval.')}</small></div>}
  </section>;
}
