import AppKit
import Combine
import UniformTypeIdentifiers
import Darwin

// Local file references only: no contents, workspace records, or remote sync.
struct NativeQuickFileShelfItem: Codable, Equatable, Identifiable {
    var id: String
    var name: String
    var path: String
    var isDirectory: Bool
    var bookmark: Data
    var identity: String
    var addedAt: Date
}

/// Revocation and the final atomic rename have one ordering. Encoding and
/// writing the temporary file happen outside this short critical section.
final class NativeQuickFileShelfCommitGate: @unchecked Sendable {
    private let lock = NSLock()
    private var valid = true
    func revoke() { lock.lock(); valid = false; lock.unlock() }
    func commit<T>(_ body: () throws -> T) throws -> T {
        lock.lock(); defer { lock.unlock() }
        guard valid else { throw CancellationError() }
        return try body()
    }
}
struct NativeQuickFileShelfRow: Identifiable, Equatable {
    let item: NativeQuickFileShelfItem
    let url: URL?
    var id: String { item.id }
    var name: String { url?.lastPathComponent ?? item.name }
    var available: Bool { url != nil }
}

enum NativeQuickFileShelfCopyError: Error { case missing(Set<String>) }

/// Holds access only while resolving and publishing an explicit copy. There are
/// no promised file contents and no clipboard listener or source-file writes.
final class NativeQuickFileShelfCopyBatch: @unchecked Sendable {
    let urls: [URL]
    private let accessed: [URL]
    init(items: [NativeQuickFileShelfItem]) throws {
        var resolved: [URL] = [], accessed: [URL] = [], missing = Set<String>()
        do {
            for item in items {
                try Task.checkCancellation()
                guard let url = NativeQuickFileShelfArchive.resolve(item) else { missing.insert(item.id); continue }
                if url.startAccessingSecurityScopedResource() { accessed.append(url) }
                resolved.append(url)
            }
            guard missing.isEmpty else { throw NativeQuickFileShelfCopyError.missing(missing) }
        } catch {
            for url in accessed { url.stopAccessingSecurityScopedResource() }
            throw error
        }
        self.urls = resolved; self.accessed = accessed
    }
    deinit { for url in accessed { url.stopAccessingSecurityScopedResource() } }
    static func resolve(_ items: [NativeQuickFileShelfItem]) async throws -> NativeQuickFileShelfCopyBatch {
        let task = Task.detached(priority: .userInitiated) { try NativeQuickFileShelfCopyBatch(items: items) }
        return try await withTaskCancellationHandler(operation: { try await task.value }, onCancel: { task.cancel() })
    }
}

/// NSURL supplies its standard file URL representations. The public marker also
/// excludes this explicit programmatic write from AI Bro's existing history.
private final class NativeQuickFileShelfURLWriter: NSObject, NSPasteboardWriting {
    static let marker = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    let url: NSURL
    init(_ url: URL) { self.url = url as NSURL }
    func writableTypes(for pasteboard: NSPasteboard) -> [NSPasteboard.PasteboardType] {
        url.writableTypes(for: pasteboard) + [Self.marker]
    }
    func writingOptions(forType type: NSPasteboard.PasteboardType, pasteboard: NSPasteboard) -> NSPasteboard.WritingOptions { [] }
    func pasteboardPropertyList(forType type: NSPasteboard.PasteboardType) -> Any? {
        type == Self.marker ? Data() : url.pasteboardPropertyList(forType: type)
    }
}

enum NativeQuickFileShelfCopy {
    @MainActor static func write(_ urls: [URL], to pasteboard: NSPasteboard) -> Bool {
        guard !urls.isEmpty, urls.allSatisfy(\.isFileURL) else { return false }
        let writers = urls.map(NativeQuickFileShelfURLWriter.init)
        pasteboard.prepareForNewContents(with: .currentHostOnly)
        return pasteboard.writeObjects(writers)
    }
}
enum NativeQuickFileShelfError: LocalizedError {
    case unavailable, invalidFile, limit, corrupt, unsafeDirectory, timedOut, capacityForUndo
    var errorDescription: String? {
        switch self {
        case .unavailable: return nativeUI("文件暂存暂不可用。", "File shelf is unavailable.")
        case .invalidFile: return nativeUI("仅支持本机可访问的文件和文件夹。", "Choose an accessible local file or folder.")
        case .limit: return nativeUI("最多暂存 100 项，请先移除不再需要的引用。", "The shelf holds 100 items. Remove unused references first.")
        case .corrupt: return nativeUI("无法读取文件暂存，已有记录未被覆盖。", "Could not read the shelf. Existing records were not overwritten.")
        case .unsafeDirectory: return nativeUI("文件暂存目录不可用，未写入任何文件。", "The shelf directory is unavailable. Nothing was written.")
        case .timedOut: return nativeUI("读取拖入的文件超时，请重试或使用添加按钮。", "Reading the dropped files timed out. Retry or use Add.")
        case .capacityForUndo: return nativeUI("空间不足以恢复这些引用，请先移除其他项。", "Remove other references before restoring this batch.")
        }
    }
}

/// Serial I/O is off the main actor. Only this small reference archive is written.
actor NativeQuickFileShelfArchive {
    static let limit = 100
    private struct State: Codable { var version = 1; var items: [NativeQuickFileShelfItem] }
    private let directory: URL
    private var file: URL { directory.appendingPathComponent("file-shelf.json") }
    private var state: State?
    private var undoBatch: [(Int, NativeQuickFileShelfItem)] = []
    init(directory: URL) { self.directory = directory }
    struct Snapshot { let rows: [NativeQuickFileShelfRow]; let canUndo: Bool; var added = 0; var duplicates = 0 }
    private func prepare() throws {
        let fm = FileManager.default
        guard directory.isFileURL else { throw NativeQuickFileShelfError.unsafeDirectory }
        if fm.fileExists(atPath: directory.path) {
            let values = try directory.resourceValues(forKeys: [.isSymbolicLinkKey, .isDirectoryKey])
            guard values.isDirectory == true, values.isSymbolicLink != true else { throw NativeQuickFileShelfError.unsafeDirectory }
        } else { try fm.createDirectory(at: directory, withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700]) }
        try fm.setAttributes([.posixPermissions: 0o700], ofItemAtPath: directory.path)
        if fm.fileExists(atPath: file.path) {
            let values = try file.resourceValues(forKeys: [.isSymbolicLinkKey, .fileSizeKey])
            guard values.isSymbolicLink != true, (values.fileSize ?? 0) <= 8 * 1024 * 1024 else { throw NativeQuickFileShelfError.corrupt }
        }
    }
    private func load() throws -> State {
        if let state { return state }
        try prepare()
        guard FileManager.default.fileExists(atPath: file.path) else { let empty = State(items: []); state = empty; return empty }
        do {
            let decoded = try JSONDecoder().decode(State.self, from: Data(contentsOf: file))
            guard decoded.version == 1, decoded.items.count <= Self.limit,
                  Set(decoded.items.map(\.id)).count == decoded.items.count,
                  decoded.items.allSatisfy({ !$0.id.isEmpty && !$0.identity.isEmpty && !$0.bookmark.isEmpty && $0.bookmark.count <= 65536 }) else { throw NativeQuickFileShelfError.corrupt }
            state = decoded; return decoded
        } catch { throw NativeQuickFileShelfError.corrupt }
    }
    private func save(_ next: State, gate: NativeQuickFileShelfCommitGate) throws {
        try Task.checkCancellation(); try prepare()
        let data = try JSONEncoder().encode(next)
        let directoryFD = open(directory.path, O_RDONLY | O_DIRECTORY | O_NOFOLLOW)
        guard directoryFD >= 0 else { throw NativeQuickFileShelfError.unsafeDirectory }
        defer { close(directoryFD) }
        let temporary = ".file-shelf-\(UUID().uuidString).tmp"
        let descriptor = openat(directoryFD, temporary, O_WRONLY | O_CREAT | O_EXCL | O_NOFOLLOW, 0o600)
        guard descriptor >= 0 else { throw POSIXError(.init(rawValue: errno) ?? .EIO) }
        defer { close(descriptor); unlinkat(directoryFD, temporary, 0) }
        try data.withUnsafeBytes { bytes in
            var offset = 0
            while offset < bytes.count {
                let count = Darwin.write(descriptor, bytes.baseAddress!.advanced(by: offset), bytes.count - offset)
                if count < 0 && errno == EINTR { continue }
                guard count > 0 else { throw POSIXError(.init(rawValue: errno) ?? .EIO) }
                offset += count
            }
        }
        guard fsync(descriptor) == 0 else { throw POSIXError(.init(rawValue: errno) ?? .EIO) }
        try Task.checkCancellation()
        try gate.commit {
            guard renameat(directoryFD, temporary, directoryFD, "file-shelf.json") == 0 else { throw POSIXError(.init(rawValue: errno) ?? .EIO) }
        }
        state = next
    }
    static func resolve(_ item: NativeQuickFileShelfItem) -> URL? {
        var stale = false
        guard let url = try? URL(resolvingBookmarkData: item.bookmark, options: [.withoutUI, .withoutMounting, .withSecurityScope], relativeTo: nil, bookmarkDataIsStale: &stale), url.isFileURL else { return nil }
        let access = url.startAccessingSecurityScopedResource(); defer { if access { url.stopAccessingSecurityScopedResource() } }
        guard FileManager.default.fileExists(atPath: url.path), FileManager.default.isReadableFile(atPath: url.path), identity(url) == item.identity else { return nil }
        return url
    }
    private static func identity(_ url: URL) -> String {
        // Resolves symlinks for duplicate detection, while the bookmark keeps the
        // user's original file reference. Never traverses folder contents.
        let canonical = url.standardizedFileURL.resolvingSymlinksInPath()
        if let attributes = try? FileManager.default.attributesOfItem(atPath: canonical.path),
           let volume = attributes[.systemNumber] as? NSNumber, let inode = attributes[.systemFileNumber] as? NSNumber {
            return "\(volume):\(inode)"
        }
        return canonical.path
    }
    private func snapshot(_ state: State) -> Snapshot {
        Snapshot(rows: state.items.map { NativeQuickFileShelfRow(item: $0, url: Self.resolve($0)) }, canUndo: !undoBatch.isEmpty)
    }
    func read() throws -> Snapshot { try Task.checkCancellation(); return snapshot(try load()) }
    func add(_ urls: [URL], gate: NativeQuickFileShelfCommitGate = NativeQuickFileShelfCommitGate()) throws -> Snapshot {
        var next = try load()
        var identities = Set(next.items.compactMap { Self.resolve($0) }.map(Self.identity))
        var added = 0, duplicates = 0
        for url in urls {
            try Task.checkCancellation()
            guard url.isFileURL, url.host == nil || url.host == "" || url.host == "localhost" else { throw NativeQuickFileShelfError.invalidFile }
            let access = url.startAccessingSecurityScopedResource(); defer { if access { url.stopAccessingSecurityScopedResource() } }
            var isDirectory: ObjCBool = false
            guard FileManager.default.fileExists(atPath: url.path, isDirectory: &isDirectory), FileManager.default.isReadableFile(atPath: url.path) else { throw NativeQuickFileShelfError.invalidFile }
            let identity = Self.identity(url)
            guard identities.insert(identity).inserted else { duplicates += 1; continue }
            guard next.items.count < Self.limit else { throw NativeQuickFileShelfError.limit }
            let bookmark = try url.bookmarkData(options: [.withSecurityScope], includingResourceValuesForKeys: nil, relativeTo: nil)
            guard bookmark.count <= 65536 else { throw NativeQuickFileShelfError.invalidFile }
            next.items.insert(.init(id: UUID().uuidString.lowercased(), name: url.lastPathComponent, path: url.path, isDirectory: isDirectory.boolValue, bookmark: bookmark, identity: identity, addedAt: Date()), at: 0)
            added += 1
        }
        if added > 0 { try save(next, gate: gate) }
        var result = snapshot(next); result.added = added; result.duplicates = duplicates; return result
    }
    func remove(_ ids: Set<String>, gate: NativeQuickFileShelfCommitGate = NativeQuickFileShelfCommitGate()) throws -> Snapshot {
        var next = try load()
        let removed = next.items.enumerated().filter { ids.contains($0.element.id) }.map { ($0.offset, $0.element) }
        guard !removed.isEmpty else { return snapshot(next) }
        next.items.removeAll { ids.contains($0.id) }
        try save(next, gate: gate); undoBatch = removed; return snapshot(next)
    }
    func undoRemoval(gate: NativeQuickFileShelfCommitGate = NativeQuickFileShelfCommitGate()) throws -> Snapshot {
        var next = try load()
        var identities = Set(next.items.compactMap { Self.resolve($0) }.map(Self.identity))
        var paths = Set(next.items.map(\.path))
        let restoring = undoBatch.filter { old in
            guard !next.items.contains(where: { $0.id == old.1.id }), paths.insert(old.1.path).inserted else { return false }
            guard let url = Self.resolve(old.1) else { return true }
            return identities.insert(Self.identity(url)).inserted
        }
        guard next.items.count + restoring.count <= Self.limit else { throw NativeQuickFileShelfError.capacityForUndo }
        for (index, item) in restoring { next.items.insert(item, at: min(index, next.items.count)) }
        try save(next, gate: gate); undoBatch = []; return snapshot(next)
    }
}

private final class NativeQuickFileShelfProviderGate: @unchecked Sendable {
    private let lock = NSLock()
    private var continuation: CheckedContinuation<URL, Error>?
    private var progress: Progress?
    init(_ continuation: CheckedContinuation<URL, Error>) { self.continuation = continuation }
    func setProgress(_ progress: Progress) { lock.lock(); let finished = continuation == nil; if !finished { self.progress = progress }; lock.unlock(); if finished { progress.cancel() } }
    func finish(_ result: Result<URL, Error>) {
        lock.lock(); let completion = continuation; continuation = nil; let progress = progress; self.progress = nil; lock.unlock()
        guard let completion else { return }; progress?.cancel(); completion.resume(with: result)
    }
}

@MainActor final class NativeQuickFileShelfStore: ObservableObject {
    @Published private(set) var rows: [NativeQuickFileShelfRow] = []
    @Published private(set) var available = false
    @Published private(set) var loaded = false
    @Published private(set) var busy = false
    @Published private(set) var error: String?
    @Published private(set) var notice: String?
    @Published private(set) var canUndo = false
    @Published var selection = Set<String>() {
        didSet { if selection != oldValue { selectionEpoch &+= 1 } }
    }
    private let archive: NativeQuickFileShelfArchive
    private var work: Task<Void, Never>?
    private var generation = 0
    @Published private(set) var visible = false
    private var reading = false
    private var copying = false
    private var selectionEpoch = 0
    private let copyResolve: @Sendable ([NativeQuickFileShelfItem]) async throws -> NativeQuickFileShelfCopyBatch
    private let copyChangeCount: @MainActor () -> Int
    private let copyWrite: @MainActor ([URL]) -> Bool
    private var commitGate = NativeQuickFileShelfCommitGate()
    init(directory: URL,
         copyResolve: @escaping @Sendable ([NativeQuickFileShelfItem]) async throws -> NativeQuickFileShelfCopyBatch = { try await NativeQuickFileShelfCopyBatch.resolve($0) },
         copyChangeCount: @escaping @MainActor () -> Int = { NSPasteboard.general.changeCount },
         copyWrite: @escaping @MainActor ([URL]) -> Bool = { NativeQuickFileShelfCopy.write($0, to: .general) }) {
        archive = NativeQuickFileShelfArchive(directory: directory)
        self.copyResolve = copyResolve; self.copyChangeCount = copyChangeCount; self.copyWrite = copyWrite
    }
    deinit { commitGate.revoke(); work?.cancel() }
    var canReceiveDrop: Bool { available && (!busy || reading) }
    func setAvailable(_ value: Bool) {
        guard value != available else { return }
        commitGate.revoke(); commitGate = NativeQuickFileShelfCommitGate(); available = value
        generation += 1; work?.cancel(); work = nil; busy = false
        reading = false; copying = false
        if value { refresh() }
        else { rows = []; selection = []; error = nil; notice = nil; loaded = false; canUndo = false }
    }
    func setVisible(_ value: Bool) {
        guard value != visible else { return }; visible = value
        if !value && copying {
            generation += 1; work?.cancel(); work = nil; copying = false; busy = false
        }
        if value && available { refresh() }
    }
    var canCopySelection: Bool {
        available && loaded && visible && !busy && !selection.isEmpty && selection.isSubset(of: Set(rows.map(\.id)))
    }
    var canPrepareDrag: Bool { available && loaded && visible && !busy }
    func rejectDrag(missing ids: Set<String>) {
        guard available else { return }
        rows = rows.map { ids.contains($0.id) ? NativeQuickFileShelfRow(item: $0.item, url: nil) : $0 }
        notice = nil
        error = ids.isEmpty
            ? nativeUI("文件拖动未能开始，引用与原件保留。请重试。", "The file drag could not start. References and originals are retained. Try again.")
            : nativeUI("\(ids.count) 个原文件不可访问，整批未开始拖动。请重新添加原件或取消选择这些项。", "\(ids.count) originals are unavailable. The whole drag was cancelled. Add the originals again or deselect those items.")
    }
    /// Selection is captured once. A missing original rejects the whole batch
    /// before touching the clipboard, rather than quietly omitting that file.
    @discardableResult func copySelection() -> Bool {
        guard canCopySelection else { return false }
        let selected = selection, token = generation, selectionToken = selectionEpoch
        // Read only the system counter after an explicit copy action. A newer
        // copy by the user owns the clipboard across the background await.
        let pasteboardToken = copyChangeCount()
        let items = rows.filter { selected.contains($0.id) }.map(\.item)
        busy = true; copying = true; error = nil; notice = nil
        work = Task { @MainActor [weak self, copyResolve] in
            do {
                let batch = try await copyResolve(items)
                guard let self, self.available, self.visible, self.generation == token, !Task.isCancelled else { return }
                defer { if self.generation == token { self.busy = false; self.copying = false; self.work = nil } }
                guard self.selectionEpoch == selectionToken, self.selection == selected else {
                    self.notice = nativeUI("选择已改变，未复制。请重新复制当前选择。", "Selection changed. Copy the current selection again."); return
                }
                guard self.copyChangeCount() == pasteboardToken else {
                    self.notice = nativeUI("剪贴板已有新内容，未覆盖。需要这些文件时请再次复制。", "The clipboard changed. Its new contents were preserved. Copy these files again if needed."); return
                }
                let copied = batch.urls.count == items.count && self.copyWrite(batch.urls)
                guard self.available, self.visible, self.generation == token else { return }
                guard copied else {
                    self.error = nativeUI("文件复制失败，引用与原件保留。请重试。", "Could not copy the files. References and originals are retained. Try again."); return
                }
                self.notice = nativeUI("已复制 \(items.count) 个文件引用，可在 Finder 中按 ⌘V 粘贴。", "Copied \(items.count) file references. Press ⌘V in Finder to paste.")
            } catch {
                guard let self, self.available, self.visible, self.generation == token, !Task.isCancelled else { return }
                self.busy = false; self.copying = false; self.work = nil
                if case NativeQuickFileShelfCopyError.missing(let ids) = error {
                    self.rows = self.rows.map { ids.contains($0.id) ? NativeQuickFileShelfRow(item: $0.item, url: nil) : $0 }
                    self.error = nativeUI("\(ids.count) 个原文件不可访问，整批未复制。请重新添加原件或取消选择这些项。", "\(ids.count) originals are unavailable. Nothing was copied. Add the originals again or deselect those items.")
                } else {
                    self.error = nativeUI("文件复制失败，引用与原件保留。请重试。", "Could not copy the files. References and originals are retained. Try again.")
                }
            }
        }
        return true
    }
    static func canAccept(_ providers: [NSItemProvider]) -> Bool {
        !providers.isEmpty && providers.allSatisfy { $0.registeredTypeIdentifiers.contains(UTType.fileURL.identifier) }
    }
    /// True means accepted for asynchronous validation, not saved/completed.
    @discardableResult func acceptProviders(_ providers: [NSItemProvider]) -> Bool {
        guard canReceiveDrop, Self.canAccept(providers) else { return false }
        guard providers.count <= NativeQuickFileShelfArchive.limit else { error = NativeQuickFileShelfError.limit.localizedDescription; return false }
        perform { [archive, commitGate] in
            var urls: [URL] = []
            // Bound active provider requests to four. A provider that never calls
            // back times out; no blocking wait occurs on the main thread.
            for start in stride(from: 0, to: providers.count, by: 4) {
                try Task.checkCancellation()
                let batch = Array(providers[start..<min(start + 4, providers.count)])
                let values = try await withThrowingTaskGroup(of: URL.self) { group in
                    for provider in batch { group.addTask { try await Self.loadURL(provider) } }
                    var values: [URL] = []; for try await url in group { values.append(url) }; return values
                }
                urls.append(contentsOf: values)
            }
            try Task.checkCancellation(); return try await archive.add(urls, gate: commitGate)
        }
        return true
    }
    nonisolated static func loadURL(_ provider: NSItemProvider, timeout: TimeInterval = 8) async throws -> URL {
        try Task.checkCancellation()
        return try await withCheckedThrowingContinuation { continuation in
            let gate = NativeQuickFileShelfProviderGate(continuation)
            let progress = provider.loadDataRepresentation(forTypeIdentifier: UTType.fileURL.identifier) { data, failure in
                if let failure { gate.finish(.failure(failure)); return }
                guard let data, data.count <= 65536, let url = URL(dataRepresentation: data, relativeTo: nil), url.isFileURL else { gate.finish(.failure(NativeQuickFileShelfError.invalidFile)); return }
                gate.finish(.success(url))
            }
            gate.setProgress(progress)
            DispatchQueue.global(qos: .utility).asyncAfter(deadline: .now() + timeout) { gate.finish(.failure(NativeQuickFileShelfError.timedOut)) }
        }
    }
    func add(_ urls: [URL]) { guard available, loaded, !busy else { return }; perform { [archive, commitGate] in try await archive.add(urls, gate: commitGate) } }
    func refresh() { guard available, !busy else { return }; perform(readOnly: true) { [archive] in try await archive.read() } }
    func removeSelection() {
        let ids = selection; guard available, !busy, !ids.isEmpty else { return }
        perform { [archive, commitGate] in try await archive.remove(ids, gate: commitGate) }
    }
    func undoRemoval() { guard available, !busy, canUndo else { return }; perform { [archive, commitGate] in try await archive.undoRemoval(gate: commitGate) } }
    func referenceUnavailable(_ id: String) {
        rows = rows.map { $0.id == id ? NativeQuickFileShelfRow(item: $0.item, url: nil) : $0 }
        error = nativeUI("无法确认原文件。它可能已移动或被替换，请重新添加；未使用同路径的其他文件。", "The original could not be verified. It may have moved or been replaced. Add it again; another file at the same path was not used.")
    }
    func resolvedSelection() -> [URL] {
        guard available else { return [] }
        var urls: [URL] = []
        for row in rows.filter({ selection.contains($0.id) }) {
            if let url = NativeQuickFileShelfArchive.resolve(row.item) { urls.append(url) }
            else { referenceUnavailable(row.id) }
        }
        return urls
    }
    func revealSelection() {
        guard available else { return }
        let urls = resolvedSelection()
        guard !urls.isEmpty else { error = nativeUI("原文件已移动或不可访问，请重新添加。", "The original files are unavailable. Add them again."); return }
        NSWorkspace.shared.activateFileViewerSelecting(urls)
    }
    func chooseFiles(onFocus: () -> Void) {
        guard available, !busy else { return }; onFocus()
        let pickerGeneration = generation
        let panel = NSOpenPanel(); panel.canChooseFiles = true; panel.canChooseDirectories = true; panel.allowsMultipleSelection = true
        panel.prompt = nativeUI("添加引用", "Add references"); panel.message = nativeUI("文件留在原处；这里只保存引用。", "Files stay where they are. Only references are saved here.")
        let completion: (NSApplication.ModalResponse) -> Void = { [weak self] response in
            guard response == .OK else { return }
            Task { @MainActor in
                guard let self, self.available, self.generation == pickerGeneration else { return }
                self.add(panel.urls)
            }
        }
        // Keep the picker owned by the island. A standalone picker makes its
        // clicks look like outside clicks and collapses the result behind it.
        if let host = NSApp.keyWindow { panel.beginSheetModal(for: host, completionHandler: completion) }
        else { panel.begin(completionHandler: completion) }
    }
    private func perform(readOnly: Bool = false, _ operation: @escaping () async throws -> NativeQuickFileShelfArchive.Snapshot) {
        work?.cancel()
        busy = true; reading = readOnly; error = nil; notice = nil; let current = generation
        work = Task { @MainActor [weak self] in
            do {
                let result = try await operation()
                guard let self, self.available, self.generation == current, !Task.isCancelled else { return }
                self.rows = result.rows; self.canUndo = result.canUndo; self.loaded = true
                self.selection.formIntersection(Set(result.rows.map(\.id)))
                if result.added > 0 { self.notice = nativeUI("已暂存 \(result.added) 个引用，原文件未移动。", "Added \(result.added) references. Originals were not moved.") }
                else if result.duplicates > 0 { self.notice = nativeUI("这些文件已在暂存中。", "These files are already on the shelf.") }
            } catch {
                guard let self, self.available, self.generation == current, !Task.isCancelled else { return }
                self.error = error.localizedDescription
            }
            guard let self, self.generation == current else { return }; self.busy = false; self.reading = false; self.work = nil
        }
    }
}
