// Runs only inside the native isolated QA workspace. Does not touch permissions or credentials.
const assert=(value,message)=>{if(!value)throw new Error('Choice QA: '+message)};
const settle=()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
assert(document.querySelectorAll('#interfaceLanguage + .native-choices [role=radio]').length===2,'language segments');
assert([...document.querySelectorAll('.permission-row select')].every(s=>s.nextElementSibling?.classList.contains('native-choices')),'all permission controls');
assert(document.querySelector('.permission-row select:disabled').nextElementSibling.querySelector('button').disabled,'risk protection stays disabled');
const dialog=document.createElement('dialog');dialog.innerHTML='<form method="dialog"><label for="qaSelect">示例项目</label><select id="qaSelect"><optgroup label="日常"><option value="zero">未归属</option></optgroup><optgroup label="课程"></optgroup></select><button>关闭</button></form>';
document.body.append(dialog);const select=dialog.querySelector('select');for(let i=1;i<10;i++){const option=document.createElement('option');option.value='p'+i;option.textContent='学习项目 '+i;option.disabled=i===9;select.lastElementChild.append(option);}select.value='p2';let changes=0;select.addEventListener('change',()=>changes++);dialog.showModal();await settle();
try{
 const trigger=select.nextElementSibling;assert(trigger.classList.contains('native-select-trigger'),'dynamic select enhancement');
 trigger.click();let panel=document.querySelector('.native-select-panel');assert(panel&&panel.matches(':popover-open'),'top-layer modal menu');
 const search=panel.querySelector('input');assert(search,'long list search');search.value='项目 7';search.dispatchEvent(new Event('input',{bubbles:true}));assert(panel.querySelectorAll('[role=option]').length===1,'search filters');panel.querySelector('[role=option]').click();assert(select.value==='p7'&&changes===1,'original change handler fires exactly once');assert(dialog.open,'selection does not submit parent dialog');
 trigger.click();panel=document.querySelector('.native-select-panel');assert(panel.querySelector('[data-value=p9]').disabled,'disabled option preserved');panel.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));assert(!document.querySelector('.native-select-panel')&&dialog.open,'escape closes list only');assert(document.activeElement===trigger,'escape restores trigger focus');
 select.value='p3';select.dispatchEvent(new Event('change',{bubbles:true}));assert(trigger.textContent.includes('学习项目 3'),'external selection synchronization');trigger.click();select.append(new Option('新增项目','new'));await settle();assert(!document.querySelector('.native-select-panel'),'stale option list closes');
 select.disabled=true;await settle();assert(trigger.disabled,'dynamic disabled synchronization');select.disabled=false;select.hidden=true;await settle();assert(trigger.hidden,'conditional hidden state');
 select.hidden=false;await settle();assert(dialog.open,'dialog remains open before final reopen');trigger.click();assert(document.querySelector('.native-select-panel').closest('dialog')===dialog,'panel belongs to original dialog');dialog.close();await settle();assert(!document.querySelector('.native-select-panel'),'closing parent removes list: '+JSON.stringify({open:dialog.open,count:document.querySelectorAll('.native-select-panel').length,expanded:trigger.getAttribute('aria-expanded'),panels:[...document.querySelectorAll('.native-select-panel')].map(p=>({inDialog:!!p.closest('dialog'),connected:p.isConnected,visible:p.matches(':popover-open')}))}));
 return 'Choice QA passed: language, permissions, disabled risk protection, dynamic controls, search, optgroups, modal popover, change event, Escape, focus, external updates, stale lists, disabled/hidden and cleanup.';
}finally{dialog.remove();}
